#!/bin/bash

gitHooksDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SCRIPTS_DIR="$(realpath ${gitHooksDir}/../scripts)"

function check-metrics-documentation() {
  "${SCRIPTS_DIR}/check-metrics-documentation"
  if [ $? -ne 0 ]; then
      echo "metrics documentation isn't up to date. check errors above"
      exit 1
  fi
}

function reformat() {
  modified_src=$(${SCRIPTS_DIR}/reformat)
  if [ -n "$modified_src" ]; then
    echo $'\e[31mthe following src files are reformatted and not staged:\e[0m'
    echo
    echo "$modified_src"
    exit 1
  fi
}

check-metrics-documentation
reformat

