#!/bin/bash

diff_output=$(./scripts/check-for-windows-drift)
if [ $? -ne 0 ] ; then
  echo $'\e[31mdiego and diego windows have diverged. output:\e[0m'
  echo
  echo "$diff_output"
  exit 1
fi

modified_packages=$(./scripts/sync-package-specs)

if [ -n "$modified_packages" ]; then
  echo $'\e[31mthe following package specs are not staged:\e[0m'
  echo
  echo "$modified_packages"
  exit 1
fi
