#!/bin/bash

# TLDR: cf_deployer *almost* works with diego. This script is a stop-gap
#       measure to allow `lite_deploy diego` to succeed.
#
# Since diego-release needs to be deployed alongside cf-release, we use
# `generate_combo_manifest` to produce the necessary manifest file.
# `generate_combo_manifest` is similar to a standard
# `generate_deployment_manifest`, but takes an additional argument that
# points to a cf-release directory.
#
# This script just acts as a shim to bridge the gap between the two worlds
# until we come up with a canonical way to compose releases.


infrastructure=$1
shift
$HOME/workspace/diego-release/generate_combo_manifest \
  $infrastructure \
  $HOME/workspace/cf-release \
  $*
