#!/bin/bash

templates=$(dirname $0)/templates

infrastructure=$1
cf_release=$2

shift
shift

function usage() {
  echo "    Usage:
    ./generate_deployment_manifest <aws|warden> /path/to/cf-release [stubs...]

    Ex:
    ~/workspace/diego-release/generate_combo_manifest aws \\
      ~/workspace/cf-release \\
      ~/workspace/deployments-aws/ketchup/cf-aws-stub.yml \\
      ~/workspace/deployments-aws/ketchup/cf-shared-secrets.yml
"
  exit 1
}

if [ "$infrastructure" != "aws" ] && [ "$infrastructure" != "warden" ]; then
  usage
fi

if [ -z "$cf_release" ]; then
  usage
fi

spiff merge \
  $templates/deployment.yml \
  $templates/jobs.yml \
  $templates/infrastructure-${infrastructure}.yml \
  $templates/diego-cf-stub.yml \
  $cf_release/templates/cf-infrastructure-${infrastructure}.yml \
  "$@"
