// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/loggregator_v2"
)

type FakeIngressServer struct {
	SenderStub        func(loggregator_v2.Ingress_SenderServer) error
	senderMutex       sync.RWMutex
	senderArgsForCall []struct {
		arg1 loggregator_v2.Ingress_SenderServer
	}
	senderReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIngressServer) Sender(arg1 loggregator_v2.Ingress_SenderServer) error {
	fake.senderMutex.Lock()
	fake.senderArgsForCall = append(fake.senderArgsForCall, struct {
		arg1 loggregator_v2.Ingress_SenderServer
	}{arg1})
	fake.recordInvocation("Sender", []interface{}{arg1})
	fake.senderMutex.Unlock()
	if fake.SenderStub != nil {
		return fake.SenderStub(arg1)
	} else {
		return fake.senderReturns.result1
	}
}

func (fake *FakeIngressServer) SenderCallCount() int {
	fake.senderMutex.RLock()
	defer fake.senderMutex.RUnlock()
	return len(fake.senderArgsForCall)
}

func (fake *FakeIngressServer) SenderArgsForCall(i int) loggregator_v2.Ingress_SenderServer {
	fake.senderMutex.RLock()
	defer fake.senderMutex.RUnlock()
	return fake.senderArgsForCall[i].arg1
}

func (fake *FakeIngressServer) SenderReturns(result1 error) {
	fake.SenderStub = nil
	fake.senderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIngressServer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.senderMutex.RLock()
	defer fake.senderMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeIngressServer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ loggregator_v2.IngressServer = new(FakeIngressServer)
