// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/gcrhelper"
)

type FakeGCRHelper struct {
	GetGCRCredentialsStub        func() (string, string, error)
	getGCRCredentialsMutex       sync.RWMutex
	getGCRCredentialsArgsForCall []struct{}
	getGCRCredentialsReturns     struct {
		result1 string
		result2 string
		result3 error
	}
	getGCRCredentialsReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 error
	}
	IsGCRRepoStub        func(string) (bool, error)
	isGCRRepoMutex       sync.RWMutex
	isGCRRepoArgsForCall []struct {
		arg1 string
	}
	isGCRRepoReturns struct {
		result1 bool
		result2 error
	}
	isGCRRepoReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGCRHelper) GetGCRCredentials() (string, string, error) {
	fake.getGCRCredentialsMutex.Lock()
	ret, specificReturn := fake.getGCRCredentialsReturnsOnCall[len(fake.getGCRCredentialsArgsForCall)]
	fake.getGCRCredentialsArgsForCall = append(fake.getGCRCredentialsArgsForCall, struct{}{})
	stub := fake.GetGCRCredentialsStub
	fakeReturns := fake.getGCRCredentialsReturns
	fake.recordInvocation("GetGCRCredentials", []interface{}{})
	fake.getGCRCredentialsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeGCRHelper) GetGCRCredentialsCallCount() int {
	fake.getGCRCredentialsMutex.RLock()
	defer fake.getGCRCredentialsMutex.RUnlock()
	return len(fake.getGCRCredentialsArgsForCall)
}

func (fake *FakeGCRHelper) GetGCRCredentialsCalls(stub func() (string, string, error)) {
	fake.getGCRCredentialsMutex.Lock()
	defer fake.getGCRCredentialsMutex.Unlock()
	fake.GetGCRCredentialsStub = stub
}

func (fake *FakeGCRHelper) GetGCRCredentialsReturns(result1 string, result2 string, result3 error) {
	fake.getGCRCredentialsMutex.Lock()
	defer fake.getGCRCredentialsMutex.Unlock()
	fake.GetGCRCredentialsStub = nil
	fake.getGCRCredentialsReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeGCRHelper) GetGCRCredentialsReturnsOnCall(i int, result1 string, result2 string, result3 error) {
	fake.getGCRCredentialsMutex.Lock()
	defer fake.getGCRCredentialsMutex.Unlock()
	fake.GetGCRCredentialsStub = nil
	if fake.getGCRCredentialsReturnsOnCall == nil {
		fake.getGCRCredentialsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 error
		})
	}
	fake.getGCRCredentialsReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeGCRHelper) IsGCRRepo(arg1 string) (bool, error) {
	fake.isGCRRepoMutex.Lock()
	ret, specificReturn := fake.isGCRRepoReturnsOnCall[len(fake.isGCRRepoArgsForCall)]
	fake.isGCRRepoArgsForCall = append(fake.isGCRRepoArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IsGCRRepoStub
	fakeReturns := fake.isGCRRepoReturns
	fake.recordInvocation("IsGCRRepo", []interface{}{arg1})
	fake.isGCRRepoMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGCRHelper) IsGCRRepoCallCount() int {
	fake.isGCRRepoMutex.RLock()
	defer fake.isGCRRepoMutex.RUnlock()
	return len(fake.isGCRRepoArgsForCall)
}

func (fake *FakeGCRHelper) IsGCRRepoCalls(stub func(string) (bool, error)) {
	fake.isGCRRepoMutex.Lock()
	defer fake.isGCRRepoMutex.Unlock()
	fake.IsGCRRepoStub = stub
}

func (fake *FakeGCRHelper) IsGCRRepoArgsForCall(i int) string {
	fake.isGCRRepoMutex.RLock()
	defer fake.isGCRRepoMutex.RUnlock()
	argsForCall := fake.isGCRRepoArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGCRHelper) IsGCRRepoReturns(result1 bool, result2 error) {
	fake.isGCRRepoMutex.Lock()
	defer fake.isGCRRepoMutex.Unlock()
	fake.IsGCRRepoStub = nil
	fake.isGCRRepoReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGCRHelper) IsGCRRepoReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isGCRRepoMutex.Lock()
	defer fake.isGCRRepoMutex.Unlock()
	fake.IsGCRRepoStub = nil
	if fake.isGCRRepoReturnsOnCall == nil {
		fake.isGCRRepoReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isGCRRepoReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGCRHelper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGCRHelper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gcrhelper.GCRHelper = new(FakeGCRHelper)
