#!/bin/bash

RELEASE=$(cd $(dirname $0)/.. && pwd)
PRE_COMMIT=${RELEASE}/.git/hooks/pre-commit

if [ ! -f ${PRE_COMMIT} ]; then
  echo "#!/bin/bash" > ${PRE_COMMIT}
  chmod +x ${PRE_COMMIT}
fi

if grep -q 'git-hooks/pre-commit' ${PRE_COMMIT}; then
  echo "pre-commit already installed."
else
  echo >> ${PRE_COMMIT}
  echo './git-hooks/pre-commit' >> ${PRE_COMMIT}
  echo "pre-commit installed."
fi
