#!/bin/bash -ex
# vim: set ft=sh

CONF_DIR=/var/vcap/jobs/rootfses/config
ROOTFS_PACKAGE=/var/vcap/packages/rootfs_cflinuxfs2
ROOTFS_DIR=$ROOTFS_PACKAGE/rootfs

if [ ! -d $ROOTFS_DIR ]; then
  mkdir -p $ROOTFS_DIR
  tar -pzxf $ROOTFS_PACKAGE/cflinuxfs2.tar.gz -C $ROOTFS_DIR
fi

rm -f $ROOTFS_DIR/usr/local/share/ca-certificates/*

# Split files on '----END CERTIFICATE-----' and increment our file counter by 1
pushd $ROOTFS_DIR
  awk -v n=1 '
    split_after == 1 {n++;split_after=0}
    /-----END CERTIFICATE-----/ {split_after=1}
    NF {print > "usr/local/share/ca-certificates/trusted_ca_" n ".crt"}' < $CONF_DIR/certs/trusted_ca.crt
popd

# have to set TMPDIR so we can mktemp inside the chrooted subshell
updated_certs=1
retry_count=0
max_retry_count=3

set +e
until [ $updated_certs -eq 0 ] || [ $retry_count -ge $max_retry_count ]; do
  echo "trying to run update-ca-certificates..."
  TMPDIR=/tmp timeout --signal=KILL 10s chroot $ROOTFS_DIR /usr/sbin/update-ca-certificates -f
  updated_certs=$?
  retry_count=$((retry_count + 1))
done
set -e

if [ $updated_certs -ne 0 ]; then
  echo "failed to setup ca certificates"
  exit 1
fi

# change modification time to invalidate garden's image cache
touch $ROOTFS_DIR

