#!/bin/bash -ex
# vim: set ft=sh

whoami

CONF_DIR=/var/vcap/jobs/rootfses/config
ROOTFS_PACKAGE=/var/vcap/packages/rootfs_cflinuxfs2
ROOTFS_DIR=$ROOTFS_PACKAGE/rootfs

if [ ! -d $ROOTFS_DIR ]; then
  mkdir -p $ROOTFS_DIR
  tar -pzxf $ROOTFS_PACKAGE/cflinuxfs2.tar.gz -C $ROOTFS_DIR
fi

rm -f $ROOTFS_DIR/usr/local/share/ca-certificates/*
cp $CONF_DIR/certs/trusted_ca.crt $ROOTFS_DIR/usr/local/share/ca-certificates/

# have to set TMPDIR so we can mktemp inside the chrooted subshell
TMPDIR=/tmp timeout --signal=KILL 10s chroot $ROOTFS_DIR /usr/sbin/update-ca-certificates -f

# change modification time to invalidate garden's image cache
touch $ROOTFS_DIR

