#!/bin/bash -e
# vim: set ft=sh

RUN_DIR=/var/vcap/sys/run/rootfses

PIDFILE=${RUN_DIR}/rootfses.pid

mkdir -p /var/vcap/sys/log/monit
exec 1>> /var/vcap/sys/log/monit/rootfses.out.log
exec 2>> /var/vcap/sys/log/monit/rootfses.err.log

case $1 in
  start)
    mkdir -p $RUN_DIR
    chown -R vcap:vcap $RUN_DIR

    echo $$ > $PIDFILE

    # Setup rootfs
    ROOTFS_PACKAGE=/var/vcap/packages/rootfs_cflinuxfs2/
    ROOTFS_DIR=$ROOTFS_PACKAGE/rootfs
    if [ ! -d $ROOTFS_DIR ]; then
      mkdir -p $ROOTFS_DIR
      tar -pzxf $ROOTFS_PACKAGE/cflinuxfs2.tar.gz -C $ROOTFS_DIR
    fi

    # wait forever
    kill -STOP $$

    ;;

  stop)
    # wake up ctl script so it exits
    pkill -F -CONT $PIDFILE

    ;;

  *)
    echo "Usage: $0 {start|stop}"
    ;;
esac
