// Code generated by counterfeiter. DO NOT EDIT.
package containerstorefakes

import (
	"sync"

	"code.cloudfoundry.org/executor"
	"code.cloudfoundry.org/executor/depot/containerstore"
	"code.cloudfoundry.org/garden"
	lager "code.cloudfoundry.org/lager/v3"
	"github.com/tedsuo/ifrit"
)

type FakeCredManager struct {
	CreateCredDirStub        func(lager.Logger, executor.Container) ([]garden.BindMount, []executor.EnvironmentVariable, error)
	createCredDirMutex       sync.RWMutex
	createCredDirArgsForCall []struct {
		arg1 lager.Logger
		arg2 executor.Container
	}
	createCredDirReturns struct {
		result1 []garden.BindMount
		result2 []executor.EnvironmentVariable
		result3 error
	}
	createCredDirReturnsOnCall map[int]struct {
		result1 []garden.BindMount
		result2 []executor.EnvironmentVariable
		result3 error
	}
	GenerateInitialCredentialsStub        func(lager.Logger, executor.Container) (containerstore.Credentials, error)
	generateInitialCredentialsMutex       sync.RWMutex
	generateInitialCredentialsArgsForCall []struct {
		arg1 lager.Logger
		arg2 executor.Container
	}
	generateInitialCredentialsReturns struct {
		result1 containerstore.Credentials
		result2 error
	}
	generateInitialCredentialsReturnsOnCall map[int]struct {
		result1 containerstore.Credentials
		result2 error
	}
	RemoveCredDirStub        func(lager.Logger, executor.Container) error
	removeCredDirMutex       sync.RWMutex
	removeCredDirArgsForCall []struct {
		arg1 lager.Logger
		arg2 executor.Container
	}
	removeCredDirReturns struct {
		result1 error
	}
	removeCredDirReturnsOnCall map[int]struct {
		result1 error
	}
	RunnerStub        func(lager.Logger, containerstore.ContainerInfoProvider, <-chan struct{}) ifrit.Runner
	runnerMutex       sync.RWMutex
	runnerArgsForCall []struct {
		arg1 lager.Logger
		arg2 containerstore.ContainerInfoProvider
		arg3 <-chan struct{}
	}
	runnerReturns struct {
		result1 ifrit.Runner
	}
	runnerReturnsOnCall map[int]struct {
		result1 ifrit.Runner
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCredManager) CreateCredDir(arg1 lager.Logger, arg2 executor.Container) ([]garden.BindMount, []executor.EnvironmentVariable, error) {
	fake.createCredDirMutex.Lock()
	ret, specificReturn := fake.createCredDirReturnsOnCall[len(fake.createCredDirArgsForCall)]
	fake.createCredDirArgsForCall = append(fake.createCredDirArgsForCall, struct {
		arg1 lager.Logger
		arg2 executor.Container
	}{arg1, arg2})
	stub := fake.CreateCredDirStub
	fakeReturns := fake.createCredDirReturns
	fake.recordInvocation("CreateCredDir", []interface{}{arg1, arg2})
	fake.createCredDirMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCredManager) CreateCredDirCallCount() int {
	fake.createCredDirMutex.RLock()
	defer fake.createCredDirMutex.RUnlock()
	return len(fake.createCredDirArgsForCall)
}

func (fake *FakeCredManager) CreateCredDirCalls(stub func(lager.Logger, executor.Container) ([]garden.BindMount, []executor.EnvironmentVariable, error)) {
	fake.createCredDirMutex.Lock()
	defer fake.createCredDirMutex.Unlock()
	fake.CreateCredDirStub = stub
}

func (fake *FakeCredManager) CreateCredDirArgsForCall(i int) (lager.Logger, executor.Container) {
	fake.createCredDirMutex.RLock()
	defer fake.createCredDirMutex.RUnlock()
	argsForCall := fake.createCredDirArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCredManager) CreateCredDirReturns(result1 []garden.BindMount, result2 []executor.EnvironmentVariable, result3 error) {
	fake.createCredDirMutex.Lock()
	defer fake.createCredDirMutex.Unlock()
	fake.CreateCredDirStub = nil
	fake.createCredDirReturns = struct {
		result1 []garden.BindMount
		result2 []executor.EnvironmentVariable
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCredManager) CreateCredDirReturnsOnCall(i int, result1 []garden.BindMount, result2 []executor.EnvironmentVariable, result3 error) {
	fake.createCredDirMutex.Lock()
	defer fake.createCredDirMutex.Unlock()
	fake.CreateCredDirStub = nil
	if fake.createCredDirReturnsOnCall == nil {
		fake.createCredDirReturnsOnCall = make(map[int]struct {
			result1 []garden.BindMount
			result2 []executor.EnvironmentVariable
			result3 error
		})
	}
	fake.createCredDirReturnsOnCall[i] = struct {
		result1 []garden.BindMount
		result2 []executor.EnvironmentVariable
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCredManager) GenerateInitialCredentials(arg1 lager.Logger, arg2 executor.Container) (containerstore.Credentials, error) {
	fake.generateInitialCredentialsMutex.Lock()
	ret, specificReturn := fake.generateInitialCredentialsReturnsOnCall[len(fake.generateInitialCredentialsArgsForCall)]
	fake.generateInitialCredentialsArgsForCall = append(fake.generateInitialCredentialsArgsForCall, struct {
		arg1 lager.Logger
		arg2 executor.Container
	}{arg1, arg2})
	stub := fake.GenerateInitialCredentialsStub
	fakeReturns := fake.generateInitialCredentialsReturns
	fake.recordInvocation("GenerateInitialCredentials", []interface{}{arg1, arg2})
	fake.generateInitialCredentialsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCredManager) GenerateInitialCredentialsCallCount() int {
	fake.generateInitialCredentialsMutex.RLock()
	defer fake.generateInitialCredentialsMutex.RUnlock()
	return len(fake.generateInitialCredentialsArgsForCall)
}

func (fake *FakeCredManager) GenerateInitialCredentialsCalls(stub func(lager.Logger, executor.Container) (containerstore.Credentials, error)) {
	fake.generateInitialCredentialsMutex.Lock()
	defer fake.generateInitialCredentialsMutex.Unlock()
	fake.GenerateInitialCredentialsStub = stub
}

func (fake *FakeCredManager) GenerateInitialCredentialsArgsForCall(i int) (lager.Logger, executor.Container) {
	fake.generateInitialCredentialsMutex.RLock()
	defer fake.generateInitialCredentialsMutex.RUnlock()
	argsForCall := fake.generateInitialCredentialsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCredManager) GenerateInitialCredentialsReturns(result1 containerstore.Credentials, result2 error) {
	fake.generateInitialCredentialsMutex.Lock()
	defer fake.generateInitialCredentialsMutex.Unlock()
	fake.GenerateInitialCredentialsStub = nil
	fake.generateInitialCredentialsReturns = struct {
		result1 containerstore.Credentials
		result2 error
	}{result1, result2}
}

func (fake *FakeCredManager) GenerateInitialCredentialsReturnsOnCall(i int, result1 containerstore.Credentials, result2 error) {
	fake.generateInitialCredentialsMutex.Lock()
	defer fake.generateInitialCredentialsMutex.Unlock()
	fake.GenerateInitialCredentialsStub = nil
	if fake.generateInitialCredentialsReturnsOnCall == nil {
		fake.generateInitialCredentialsReturnsOnCall = make(map[int]struct {
			result1 containerstore.Credentials
			result2 error
		})
	}
	fake.generateInitialCredentialsReturnsOnCall[i] = struct {
		result1 containerstore.Credentials
		result2 error
	}{result1, result2}
}

func (fake *FakeCredManager) RemoveCredDir(arg1 lager.Logger, arg2 executor.Container) error {
	fake.removeCredDirMutex.Lock()
	ret, specificReturn := fake.removeCredDirReturnsOnCall[len(fake.removeCredDirArgsForCall)]
	fake.removeCredDirArgsForCall = append(fake.removeCredDirArgsForCall, struct {
		arg1 lager.Logger
		arg2 executor.Container
	}{arg1, arg2})
	stub := fake.RemoveCredDirStub
	fakeReturns := fake.removeCredDirReturns
	fake.recordInvocation("RemoveCredDir", []interface{}{arg1, arg2})
	fake.removeCredDirMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCredManager) RemoveCredDirCallCount() int {
	fake.removeCredDirMutex.RLock()
	defer fake.removeCredDirMutex.RUnlock()
	return len(fake.removeCredDirArgsForCall)
}

func (fake *FakeCredManager) RemoveCredDirCalls(stub func(lager.Logger, executor.Container) error) {
	fake.removeCredDirMutex.Lock()
	defer fake.removeCredDirMutex.Unlock()
	fake.RemoveCredDirStub = stub
}

func (fake *FakeCredManager) RemoveCredDirArgsForCall(i int) (lager.Logger, executor.Container) {
	fake.removeCredDirMutex.RLock()
	defer fake.removeCredDirMutex.RUnlock()
	argsForCall := fake.removeCredDirArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCredManager) RemoveCredDirReturns(result1 error) {
	fake.removeCredDirMutex.Lock()
	defer fake.removeCredDirMutex.Unlock()
	fake.RemoveCredDirStub = nil
	fake.removeCredDirReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCredManager) RemoveCredDirReturnsOnCall(i int, result1 error) {
	fake.removeCredDirMutex.Lock()
	defer fake.removeCredDirMutex.Unlock()
	fake.RemoveCredDirStub = nil
	if fake.removeCredDirReturnsOnCall == nil {
		fake.removeCredDirReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeCredDirReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCredManager) Runner(arg1 lager.Logger, arg2 containerstore.ContainerInfoProvider, arg3 <-chan struct{}) ifrit.Runner {
	fake.runnerMutex.Lock()
	ret, specificReturn := fake.runnerReturnsOnCall[len(fake.runnerArgsForCall)]
	fake.runnerArgsForCall = append(fake.runnerArgsForCall, struct {
		arg1 lager.Logger
		arg2 containerstore.ContainerInfoProvider
		arg3 <-chan struct{}
	}{arg1, arg2, arg3})
	stub := fake.RunnerStub
	fakeReturns := fake.runnerReturns
	fake.recordInvocation("Runner", []interface{}{arg1, arg2, arg3})
	fake.runnerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCredManager) RunnerCallCount() int {
	fake.runnerMutex.RLock()
	defer fake.runnerMutex.RUnlock()
	return len(fake.runnerArgsForCall)
}

func (fake *FakeCredManager) RunnerCalls(stub func(lager.Logger, containerstore.ContainerInfoProvider, <-chan struct{}) ifrit.Runner) {
	fake.runnerMutex.Lock()
	defer fake.runnerMutex.Unlock()
	fake.RunnerStub = stub
}

func (fake *FakeCredManager) RunnerArgsForCall(i int) (lager.Logger, containerstore.ContainerInfoProvider, <-chan struct{}) {
	fake.runnerMutex.RLock()
	defer fake.runnerMutex.RUnlock()
	argsForCall := fake.runnerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCredManager) RunnerReturns(result1 ifrit.Runner) {
	fake.runnerMutex.Lock()
	defer fake.runnerMutex.Unlock()
	fake.RunnerStub = nil
	fake.runnerReturns = struct {
		result1 ifrit.Runner
	}{result1}
}

func (fake *FakeCredManager) RunnerReturnsOnCall(i int, result1 ifrit.Runner) {
	fake.runnerMutex.Lock()
	defer fake.runnerMutex.Unlock()
	fake.RunnerStub = nil
	if fake.runnerReturnsOnCall == nil {
		fake.runnerReturnsOnCall = make(map[int]struct {
			result1 ifrit.Runner
		})
	}
	fake.runnerReturnsOnCall[i] = struct {
		result1 ifrit.Runner
	}{result1}
}

func (fake *FakeCredManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCredManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ containerstore.CredManager = new(FakeCredManager)
