#!/bin/bash

set -e
set -o

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

function usage() {
  >&2 cat <<EOF
  SYNOPSIS:
    Create a CloudFormation stack, deploy BOSH, and create initial CF and Diego stubs.

  USAGE:
    $0 (create|update|skip) CF_RELEASE_DIR DEPLOYMENT_DIR [STACK_NAME]

  MANDATORY ARGUMENTS:
    CF_RELEASE_DIR:     Path to the local cf-release repository.
    DEPLOYMENT_DIR:     Directory to store files for this deployment.

  OPTIONAL ARGUMENTS:
    STACK_NAME:         Name of the CloudFormation stack to create (default: cf-diego-stack)
EOF
  exit 1
}


indent() {
  sed -e 's/^/  /'
}

indent_contents_of() {
  indent < "$1"
}

block() {
  cat <<-EOF
$1: |
$(indent_contents_of "$2")
EOF
}

cf_credentials() {
  cat <<-EOF
# GENERATED: NO TOUCHING
---
cf_credentials:
  ssh_host_key_fingerprint: "$(cat keypair/ssh-proxy-host-key-fingerprint)"
  consul:
$(block ca_cert     certs/consul-certs/server-ca.crt | indent | indent)
$(block agent_cert  certs/consul-certs/agent.crt     | indent | indent)
$(block agent_key   certs/consul-certs/agent.key     | indent | indent)
$(block server_cert certs/consul-certs/server.crt    | indent | indent)
$(block server_key  certs/consul-certs/server.key    | indent | indent)
  uaa:
$(block signing_key      keypair/uaa     | indent | indent)
$(block verification_key keypair/uaa.pub | indent | indent)

EOF
}

diego_credentials() {
  cat <<-EOF
# GENERATED: NO TOUCHING
---
diego_credentials:
$(block diego_ca           certs/diego-ca.crt             | indent)
$(block ssh_proxy_host_key keypair/ssh-proxy-host-key.pem | indent)
  bbs:
$(block client_cert certs/bbs-certs/client.crt  | indent | indent)
$(block client_key  certs/bbs-certs/client.key  | indent | indent)
$(block server_cert certs/bbs-certs/server.crt  | indent | indent)
$(block server_key  certs/bbs-certs/server.key  | indent | indent)
  etcd:
$(block client_cert certs/etcd-certs/client.crt | indent | indent)
$(block client_key  certs/etcd-certs/client.key | indent | indent)
$(block server_cert certs/etcd-certs/server.crt | indent | indent)
$(block server_key  certs/etcd-certs/server.key | indent | indent)
$(block peer_ca     certs/etcd-peer-ca.crt      | indent | indent)
$(block peer_cert   certs/etcd-certs/peer.crt   | indent | indent)
$(block peer_key    certs/etcd-certs/peer.key   | indent | indent)
EOF
}


if [ "$1" == "create" ]; then
  UPDATE_OR_CREATE=create-stack
elif [ "$1" == "update" ]; then
  UPDATE_OR_CREATE=update-stack
elif [ "$1" == "skip" ]; then
  UPDATE_OR_CREATE="skip"
else
  usage
  exit 1
fi

cf_release_dir=$2
deployment_dir=$3
stack_name=${4:-cf-diego-stack}

if [ -z ${deployment_dir} ]; then
  usage
fi

command -v aws >/dev/null || { echo "aws is required"; exit 1; }
command -v jq >/dev/null || { echo "jq is required"; exit 1; }
command -v spiff >/dev/null || { echo "spiff is required"; exit 1; }
command -v bosh-init >/dev/null || { echo "bosh-init is required"; exit 1; }

set -x

pushd ${deployment_dir}

mkdir -p stubs/cf
mkdir -p stubs/infrastructure
mkdir -p deployments/bosh-init

source bootstrap_environment

# install certs for ELB
if ! aws iam get-server-certificate --server-certificate-name cfrouter; then
  aws iam upload-server-certificate                   \
    --server-certificate-name cfrouter                \
    --private-key file://certs/elb-cfrouter.key       \
    --certificate-body file://certs/elb-cfrouter.pem
fi

# generate stub to be fed into template for cloudformation
cat > stubs/infrastructure/certificates.yml <<EOF
# GENERATED: NO TOUCHING
EOF

aws iam get-server-certificate --server-certificate-name cfrouter \
  >> stubs/infrastructure/certificates.yml

# generate cloudformation template
spiff merge \
  $SCRIPT_DIR/templates/infrastructure/boosh.yml \
  $SCRIPT_DIR/templates/infrastructure/boosh-internal.yml \
  stubs/bosh-init/keypair.yml \
  stubs/domain.yml \
  stubs/infrastructure/certificates.yml \
  stubs/infrastructure/availability_zones.yml \
  | boosh generate | jq -c -S . \
  > stubs/infrastructure/cloudformation.json

# deploy infrastructure
if [ $UPDATE_OR_CREATE != "skip" ]; then
  aws cloudformation $UPDATE_OR_CREATE \
    --stack-name $stack_name \
    --template-body file://stubs/infrastructure/cloudformation.json

  # ensure that create or update was successful to aws
  boosh watch --name $stack_name
  # generate AWS resources stub for shared purposes
  cat > stubs/aws-resources.yml <<EOF
# GENERATED: NO TOUCHING
EOF

  boosh resources --name $stack_name >> stubs/aws-resources.yml
fi

cat > deployments/bosh-init/bosh-init.yml <<EOF
# GENERATED: NO TOUCHING
EOF

spiff merge \
  $SCRIPT_DIR/templates/bosh-init/bosh-init.yml \
  $SCRIPT_DIR/templates/bosh-init/bosh-init-internal.yml \
  stubs/aws-resources.yml \
  stubs/bosh-init/*.yml \
  >> deployments/bosh-init/bosh-init.yml

bosh-init deploy deployments/bosh-init/bosh-init.yml
bosh -n target $(cat stubs/aws-resources.yml | grep BoshInit | awk '{ gsub(/"/, "", $NF); print $NF }')

# generate director uuid stub for template to create deployment stub
cat > stubs/director-uuid.yml <<EOF
# GENERATED: NO TOUCHING
---
director_uuid: $(bosh status --uuid | tr -d '\n')
EOF

# generate stub with deployment base domain
cat > stubs/cf/domain.yml <<EOF
# GENERATED: NO TOUCHING
EOF

spiff merge $SCRIPT_DIR/templates/cf/domain.yml \
  $SCRIPT_DIR/templates/cf/domain-internal.yml \
  stubs/domain.yml \
  >> stubs/cf/domain.yml

# generate deployment stub
cat > stubs/cf/stub.yml <<EOF
# GENERATED: NO TOUCHING
EOF

spiff merge \
  $SCRIPT_DIR/templates/cf/stub.yml \
  $SCRIPT_DIR/templates/cf/stub-internal.yml \
  stubs/aws-resources.yml \
  stubs/cf/domain.yml \
  stubs/director-uuid.yml \
  <(cf_credentials) \
  >> stubs/cf/stub.yml

# copy CF property stub if not already present
if [ ! -f stubs/cf/properties.yml ]; then
  cp $SCRIPT_DIR/stubs/cf/properties.yml stubs/cf/properties.yml
fi

mkdir -p stubs/diego

# generate Diego property-override stub with certs
if [ -f stubs/diego/property-overrides.yml ]; then
  # update BBS, etcd certs and keys in existing property-overrides stub
  temp_property_overrides=$(mktemp stubs/diego/property-overrides.yml.XXXXX)

  spiff merge \
    stubs/diego/property-overrides.yml \
    $SCRIPT_DIR/templates/diego/property-overrides-internal.yml \
    <(diego_credentials) \
    > "${temp_property_overrides}"

  mv "${temp_property_overrides}" stubs/diego/property-overrides.yml
else
  # create new property-overrides stub with default overrides
  spiff merge \
    $SCRIPT_DIR/templates/diego/property-overrides.yml \
    $SCRIPT_DIR/templates/diego/property-overrides-internal.yml \
    <(diego_credentials) \
    > stubs/diego/property-overrides.yml
fi

# generate Diego IaaS-settings stub
spiff merge \
  $SCRIPT_DIR/../../manifest-generation/misc-templates/aws-iaas-settings.yml \
  $SCRIPT_DIR/templates/diego/iaas-settings-internal.yml \
  stubs/aws-resources.yml \
  > stubs/diego/iaas-settings.yml

mkdir -p stubs/cf-mysql

# generate CF-MySQL IaaS-settings stub
spiff merge \
  $SCRIPT_DIR/templates/mysql/iaas-settings.yml \
  $SCRIPT_DIR/templates/mysql/iaas-settings-internal.yml \
  stubs/aws-resources.yml \
  > stubs/cf-mysql/iaas-settings.yml

popd
