#!/bin/bash

set -e -x

docker run -a stdout -a stderr -w /root/workspace \
  -v $PWD:/root/workspace \
  -v $PWD/bosh-cache:/root/.bosh/cache \
  -e GOROOT=/usr/local/go \
  -e BOSH_PASSWORD \
  -e BOSH_TARGET \
  -e BOSH_USER \
  -e DEPLOYMENT_NAME \
  -e DATADOG_API_KEY \
  -e DEPLOYMENT_DIR \
  -e STUBS_DIR \
  -e INFRASTRUCTURE \
  cloudfoundry/diego-pipeline \
  /bin/bash -l diego-release/scripts/ci/create_cf_release_inner

