#!/bin/bash

set -e -x -u

mkdir -p "output"
OUTPUT_DIR="$PWD/output"

echo "----- Configure git to use our ssh key"
export GIT_SSH=$(pwd)/tmp/git_ssh.sh
chmod 600 $(pwd)/tmp/github
echo "ssh -i $(pwd)/tmp/github" '"$@"' > $GIT_SSH
chmod +x $GIT_SSH

echo "----- Create dev release" # to work around https://www.pivotaltracker.com/story/show/74823266
bosh -n create release

echo "----- Create final release"
bosh -n create release --final --with-tarball --version 0.$GO_PIPELINE_COUNTER

echo "----- Move tarball to ${OUTPUT_DIR} for artifact publishing"
mv releases/*.tgz "${OUTPUT_DIR}/diego-final-release-created-by-ci.tgz"

echo "----- Set git identity"
git config user.email "cf-diego@pivotallabs.com"
git config user.name "CI (Automated)"

echo "----- Update master and develop branches on origin"
git add -A
git commit -m "Create final release for build $GO_PIPELINE_COUNTER"


echo "----- Merge final-release into master"
git fetch origin master
git merge origin/master
git push origin HEAD:master

echo "----- Merge final-release from master back into develop"
git fetch origin develop
git merge origin/develop
git push origin HEAD:develop
