#!/bin/bash
set -e -x -u

export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

pushd cf-release
  echo "----- Create dev release"
  version=$(date "+%s")
  bosh --parallel 10 -n create release --version ${version} --with-tarball

  mv dev_releases/cf/*.tgz ../cf-dev-release-${version}.tgz
popd
