#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

mkdir -p diego-release/tmp
cp runtime-credentials/diego-ci/ssh_keys/diego-release-push-pull diego-release/tmp/github
cp runtime-credentials/diego-ci/private.yml diego-release/config/private.yml

pushd diego-release
  ./scripts/ci/create_drone_yml scripts/ci/create_final_release.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd

mv $DRONE_TMP/diego-release/HEAD/var/cache/drone/src/diego-release/output/*.tgz .
