#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

pushd cf-release
  git submodule update --init --recursive
popd

rm -rf diego-release/cf-release || true
cp -R cf-release diego-release/

rm -rf diego-release/deployments-runtime || true
cp -R deployments-runtime diego-release/

rm -rf diego-release/light-bosh-stemcell-latest-aws-xen-ubuntu-trusty-go_agent.tgz || true
cp light-bosh-stemcell-latest-aws-xen-ubuntu-trusty-go_agent.tgz diego-release/

pushd diego-release
  ./scripts/create_drone_yml scripts/ci/create_cf_release.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd
