#!/bin/bash

set -e -x -u

echo "----- Copy private blobstore credentials into diego-release"
cp runtime-credentials/diego-ci/private.yml diego-release/config/private.yml

FINAL_RELEASE_VERSION=$(cat version/number)

pushd diego-release
  git fetch origin master
  git merge --no-edit origin/master

  echo "----- Create final release"
  bosh -n create release --final --with-tarball --version $FINAL_RELEASE_VERSION

  mv releases/diego/*.tgz ../diego-$FINAL_RELEASE_VERSION.tgz

  echo "----- Set git identity"
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  echo "----- Update master and develop branches on origin"
  git add -A
  git commit -m "Create final release ${FINAL_RELEASE_VERSION}"

  echo "----- DEBUG: show the commit we just created"
  git --no-pager show HEAD
popd
