#!/bin/bash
set -e -x -u

export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

pushd cf-release
  echo "----- Create dev release"
  bosh -n create release --version $(date "+%s") --with-tarball

  mv dev_releases/cf/*.tgz ../cf-dev-release-$(date "+%s").tgz
popd
