#!/bin/bash

set -e -x -u

STUBS_DIR=${PWD}/deployments-runtime/${DEPLOYMENT_NAME}/stubs

eval $(./scripts/ci/bosh_config)
./scripts/ci/bosh_setup

bosh -n create release --with-tarball
bosh -n upload release --rebase || true

./scripts/generate-deployment-manifest aws cf-release ${STUBS_DIR}/* > diego-deployment.yml
bosh deployment diego-deployment.yml

./scripts/ci/emit-datadog-deploy-event started cf-${DEPLOYMENT_NAME} diego
if bosh -n deploy; then
  ./scripts/ci/emit-datadog-deploy-event finished cf-${DEPLOYMENT_NAME} diego
else
  ./scripts/ci/emit-datadog-deploy-event failed cf-${DEPLOYMENT_NAME} diego
  exit 1
fi
