#!/bin/bash

set -e -x -u

STUBS_DIR=${PWD}/deployments-runtime/${DEPLOYMENT_NAME}/stubs

eval $(./scripts/ci/bosh_config)
./scripts/ci/bosh_setup

pushd cf-release
  bosh -n create release --with-tarball
  bosh -n upload release --rebase || true
  ./generate_deployment_manifest aws ${STUBS_DIR}/* > cf-deployment.yml
  bosh deployment cf-deployment.yml

  yes yes | bosh deploy
popd
