#!/bin/bash

set -e -x -u

STUBS_DIR=${PWD}/deployments-runtime/${DEPLOYMENT_NAME}/stubs

eval $(./diego-release/scripts/ci/bosh_config)
./diego-release/scripts/ci/bosh_setup

pushd cf-release
  git submodule update --init --recursive
  bosh -n create release --with-tarball
  bosh -n upload release --rebase || true
  ./generate_deployment_manifest aws ${STUBS_DIR}/* > cf-deployment.yml
  bosh deployment cf-deployment.yml

  ../diego-release/scripts/ci/emit-datadog-deploy-event started cf-${DEPLOYMENT_NAME} cf
  if bosh -n deploy; then
    ../diego-release/scripts/ci/emit-datadog-deploy-event finished cf-${DEPLOYMENT_NAME} cf
  else
    ../diego-release/scripts/ci/emit-datadog-deploy-event failed cf-${DEPLOYMENT_NAME} cf
    exit 1
  fi
popd
