#!/bin/bash

set -e -x -u

STUBS_DIR=${PWD}/deployments-runtime/${DEPLOYMENT_NAME}/stubs

./scripts/bosh_setup

bosh -n create release --with-tarball
bosh -n upload release --rebase --skip-if-exists || true

./generate_deployment_manifest aws cf-release ${STUBS_DIR}/* > diego-deployment.yml
bosh deployment diego-deployment.yml
yes yes | bosh deploy
