#!/bin/bash

set -e -x -u

stubs_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}/stubs"
cf_deployment_name="cf-${ENVIRONMENT_NAME}"

# add writable location for gems for prepackaging
export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

./diego-release/scripts/ci/bosh_setup

bosh -n cleanup

bosh -n upload stemcell bosh-stemcell/*.tgz --skip-if-exists

pushd cf-release
  bosh -n create release
  bosh -n upload release --rebase || true
  ./generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/cf/*.yml \
    > cf-deployment.yml
  bosh deployment cf-deployment.yml

  ../diego-release/scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} cf
  if bosh -n deploy; then
    ../diego-release/scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} cf
  else
    ../diego-release/scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} cf
    exit 1
  fi
popd
