#!/bin/bash

set -e -x -u

docker_registry_manifest="${PWD}/${DOCKER_REGISTRY_MANIFEST}"

./diego-release/scripts/ci/bosh_setup

pushd docker-registry-release
  bosh -n create release
  bosh -n upload release --rebase || true

  bosh deployment ${docker_registry_manifest}

  bosh -n deploy
popd
