#!/bin/bash

set -e -x -u

environment_path="${PWD}/deployments-runtime/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"
version=`cat version/number`

cf_deployment_name="cf-${ENVIRONMENT_NAME}"

./diego-release/scripts/ci/bosh_setup

pushd diego-release
  bosh -n create release --with-tarball --version $version

  mv dev_releases/diego/*.tgz ../dev-release.tgz

  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/diego/iaas-settings-internal.yml \
    ${stubs_path}/aws-resources.yml \
    > /tmp/iaas-settings.yml

  bosh download manifest ${cf_deployment_name} > /tmp/cf.yml

  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/diego/property-overrides.yml \
    ${stubs_path}/diego/instance-count-overrides.yml \
    ${stubs_path}/diego/persistent-disk-overrides.yml \
    /tmp/iaas-settings.yml \
    ${stubs_path}/diego/additional-jobs.yml \
    /tmp \
    > ../diego-deployment.yml
popd
