#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

cf_deployment_name="cf-${ENVIRONMENT_NAME}"
tmpdir=$(mktemp -d /tmp/deploy-diego.XXXXX)

./diego-release/scripts/ci/bosh_setup

bosh -n cleanup

bosh -n upload stemcell bosh-stemcell/*.tgz --skip-if-exists

pushd diego-release
  bosh -n create release
  bosh -n upload release --rebase || true

  bosh download manifest ${cf_deployment_name} > ${tmpdir}/cf.yml
  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/diego/iaas-settings-internal.yml \
    ${tmpdir}/cf.yml \
    > ${tmpdir}/iaas-settings.yml
  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/diego/property-overrides.yml \
    ${stubs_path}/diego/instance-count-overrides.yml \
    ${stubs_path}/diego/persistent-disk-overrides.yml \
    ${tmpdir}/iaas-settings.yml \
    ${tmpdir} \
    > ${tmpdir}/diego-deployment.yml
  bosh deployment ${tmpdir}/diego-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} diego
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} diego
  else
    ./scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} diego
    exit 1
  fi
popd
