#!/bin/bash

set -e -x -u

stubs_path="${PWD}/${DEPLOYMENTS_DIR}/${DEPLOYMENT_NAME}/${STUBS_DIR}"
cf_deployment_name="cf-${DEPLOYMENT_NAME}"

pushd diego-release
  ./scripts/ci/bosh_setup

  bosh -n cleanup

  bosh -n upload stemcell bosh-stemcell/*.tgz --skip-if-exists

  bosh -n create release
  bosh -n upload release --rebase || true

  bosh download manifest ${cf_deployment_name} > ${TMPDIR}/cf.yml
  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${stubs_path}/../misc-templates/iaas-settings-internal.yml \
    ${TMPDIR}/cf.yml \
    > ${TMPDIR}/iaas-settings.yml
  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/diego/property-overrides.yml \
    ${stubs_path}/diego/instance-count-overrides.yml \
    ${stubs_path}/diego/persistent-disk-overrides.yml \
    ${TMPDIR}/iaas-settings.yml \
    ${TMPDIR} \
    > ${TMPDIR}/diego-deployment.yml
  bosh deployment ${TMPDIR}/diego-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} diego
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} diego
  else
    ./scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} diego
    exit 1
  fi
popd
