#!/bin/bash

set -e -x -u

stubs_path="${PWD}/deployments-runtime/${ENVIRONMENT_NAME}/stubs"
cf_deployment_name="cf-${ENVIRONMENT_NAME}"

# add writable location for gems for prepackaging
export GEM_HOME="${HOME}/.gem"
mkdir -p "${GEM_HOME}"

pushd cf-release
  bosh -n create release --version $(date "+%s") --with-tarball

  mv dev_releases/cf/*.tgz ../dev-release.tgz

  ./generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/cf/*.yml \
    > ../cf-deployment.yml
popd
