#!/bin/bash

set -e -x -u

environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"

cf_deployment_name="cf-${ENVIRONMENT_NAME}"
tmpdir=$(mktemp -d /tmp/deploy-diego-final.XXXXX)

FINAL_RELEASE_VERSION=$(cat version/number)

pushd diego-release
  ./scripts/ci/bosh_setup

  bosh -n cleanup

  latest_final_release="releases/diego-${FINAL_RELEASE_VERSION}.yml"
  if [[ ! -f $latest_final_release ]]; then
    exit 1
  fi
  bosh -n upload release $latest_final_release --skip-if-exists || true

  bosh download manifest ${cf_deployment_name} > ${tmpdir}/cf.yml
  spiff merge \
    manifest-generation/misc-templates/iaas-settings.yml \
    ${templates_path}/diego/iaas-settings-internal.yml \
    ${tmpdir}/cf.yml \
    > ${tmpdir}/iaas-settings.yml
  ./scripts/generate-deployment-manifest \
    ${stubs_path}/director-uuid.yml \
    ${stubs_path}/diego/property-overrides.yml \
    ${stubs_path}/diego/instance-count-overrides.yml \
    ${stubs_path}/diego/persistent-disk-overrides.yml \
    ${tmpdir}/iaas-settings.yml \
    ${stubs_path}/diego/additional-jobs.yml \
    ${tmpdir} \
    > ${tmpdir}/diego-deployment.yml
  bosh deployment ${tmpdir}/diego-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started ${cf_deployment_name} diego
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished ${cf_deployment_name} diego
  else
    ./scripts/ci/emit-datadog-deploy-event failed ${cf_deployment_name} diego
    exit 1
  fi
popd
