#!/bin/bash

set -e -x -u
stubs_path="${PWD}/${DEPLOYMENTS_DIR}/${DEPLOYMENT_NAME}/${STUBS_DIR}"

(
  cd diego-release
  eval $(./scripts/ci/bosh_config)
  ./scripts/ci/bosh_setup

  latest_final_release=$(ls releases/diego-*.yml | sort -n | tail -n1)
  bosh -n upload release $latest_final_release --skip-if-exists || true

  ./scripts/generate-deployment-manifest ${INFRASTRUCTURE} ../cf-release ${stubs_path}/* > diego-deployment.yml
  bosh deployment diego-deployment.yml

  ./scripts/ci/emit-datadog-deploy-event started cf-${DEPLOYMENT_NAME} diego
  if bosh -n deploy; then
    ./scripts/ci/emit-datadog-deploy-event finished cf-${DEPLOYMENT_NAME} diego
  else
    ./scripts/ci/emit-datadog-deploy-event failed cf-${DEPLOYMENT_NAME} diego
    exit 1
  fi
)
