#!/bin/bash

set -e -x -u

STUBS_DIR=${PWD}/deployments-aws/${DEPLOYMENT_NAME}/stubs

eval $(./scripts/ci/bosh_config)
./scripts/ci/bosh_setup

bosh -n upload release diego-final-release-created-by-ci.tgz --skip-if-exists || true

./generate_deployment_manifest aws cf-release ${STUBS_DIR}/* > diego-deployment.yml
bosh deployment diego-deployment.yml

./scripts/ci/emit-datadog-deploy-event started ${DEPLOYMENT_NAME} diego
yes yes | bosh deploy
./scripts/ci/emit-datadog-deploy-event finished ${DEPLOYMENT_NAME} diego
