#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

rm -rf "diego-release/${DEPLOYMENTS_DIR}"
cp -R "${DEPLOYMENTS_DIR}" diego-release/

rm -rf diego-release/cf-release
cp -R cf-release diego-release/

rm -f diego-release/diego-final-release-created-by-ci.tgz
cp diego-final-release-created-by-ci.tgz diego-release/

pushd diego-release
  ./scripts/ci/create_drone_yml scripts/ci/diego_deploy.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd
