#!/bin/bash

set -e -x -u

STUBS_DIR=${PWD}/deployments-aws/${DEPLOYMENT_NAME}/stubs

eval $(./scripts/ci/bosh_config)
./scripts/ci/bosh_setup

bosh -n upload release diego-final-release-created-by-ci.tgz --skip-if-exists || true

./scripts/generate-deployment-manifest aws cf-release ${STUBS_DIR}/* > diego-deployment.yml
bosh deployment diego-deployment.yml

./scripts/ci/emit-datadog-deploy-event started ${DEPLOYMENT_NAME} diego
if bosh -n deploy; then
  ./scripts/ci/emit-datadog-deploy-event finished ${DEPLOYMENT_NAME} diego
else
  ./scripts/ci/emit-datadog-deploy-event failed ${DEPLOYMENT_NAME} diego
  exit 1
fi
