#!/bin/bash

set -e -x -u

state=$1
environment=$2
deployment=$3

curl  -X POST -H "Content-type: application/json" -d "{                   \
    \"title\": \"${state} deploying ${deployment} to ${environment}\",    \
    \"text\": \"${state} deploying ${deployment} to ${environment}\",     \
    \"priority\": \"normal\",                                             \
    \"tags\": [\"deployment:${environment}-${deployment}\"],              \
    \"alert_type\": \"info\"                                              \
  }" "https://app.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"
