#!/bin/bash

set -e -x -u

metric_value=$1
deployment_tag=$2
time_stamp=`date +%s`

curl  -X POST -H "Content-type: application/json" -d "{                   \
    \"series\": [{                                                        \
      \"metric\":\"diego.smoke.status\",                                  \
      \"points\":[[${time_stamp}, ${metric_value}]],                      \
      \"type\":\"gauge\",                                                 \
      \"tags\":[\"deployment:${deployment_tag}\"]                         \
    ]}                                                                    \
  }" "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}"

