#!/bin/bash

set -e -x -u

canary_app_errand_manifest=${PWD}/${CANARY_APP_ERRAND_MANIFEST}

./diego-release/scripts/ci/bosh_setup

bosh deployment ${canary_app_errand_manifest}
bosh -n deploy
bosh run errand push_canary_app --keep-alive

