#!/bin/bash

set -e -x -u

./diego-release/scripts/ci/bosh_setup
tmpdir=$(mktemp -d /tmp/compatibility.XXXXX)

current_date=$(date)
bosh deployments > ${tmpdir}/deployments
bosh releases > ${tmpdir}/releases
cf_data=$(./diego-release/scripts/ci/extract-release-and-sha \
          ${tmpdir}/deployments \
          ${tmpdir}/releases \
          cf \
        )
diego_data=$(./diego-release/scripts/ci/extract-release-and-sha \
             ${tmpdir}/deployments \
             ${tmpdir}/releases \
             diego \
           )
new_row=${current_date},${RELEASE_STAGE},${cf_data},${diego_data}

pushd diego-cf-compatibility
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  echo ${new_row} >> compatibility.csv
  git add compatibility.csv
  git commit -m "Add CF-Diego compatibility record on ${current_date} at release stage ${RELEASE_STAGE}"
popd
