#!/bin/bash

set -e -x -u

./diego-release/scripts/ci/bosh_setup

current_date=$(date)
director_version=$(bosh status | grep Version | tr -s ' ' | cut -f3 -d' ')

stemcell_manifest=$(tar zxvOf bosh-stemcell/stemcell.tgz stemcell.MF 2>/dev/null)
stemcell_name=$(echo "${stemcell_manifest}" | grep ^name | cut -f2 -d: | tr -d ' ')
stemcell_version=$(echo "${stemcell_manifest}" | grep ^version | cut -f2 -d: | tr -d "'" | tr -d ' ')
stemcell="${stemcell_name}/${stemcell_version}"

cf_release_manifest=$(tar zxvOf cf-dev-release/*.tgz ./release.MF 2>/dev/null)
cf_release_sha=$(echo "${cf_release_manifest}" | grep ^commit_hash | cut -f2 -d: | tr -d "'" | tr -d ' ')

diego_release_manifest=$(tar zxvOf diego-dev-release/*.tgz ./release.MF 2>/dev/null)
diego_release_version="N/A"
if [ $ENVIRONMENT_NAME == "a1" ]
then
  diego_release_version=$(echo "${diego_release_manifest}" | grep ^version | cut -f2 -d: | tr -d "'" | tr -d ' ')
fi
diego_release_sha=$(echo "${diego_release_manifest}" | grep ^commit_hash | cut -f2 -d: | tr -d "'" | tr -d ' ')

new_row=${current_date},${RELEASE_STAGE},${director_version},${cf_release_sha},${stemcell},${diego_release_version},${diego_release_sha},${stemcell}

pushd diego-cf-compatibility
  git config user.email "cf-diego@pivotal.io"
  git config user.name "CI (Automated)"

  echo ${new_row} >> compatibility-v1.csv
  git add compatibility.csv || true
  git add compatibility-v1.csv || true
  git commit -m "Add CF-Diego compatibility record on ${current_date} at release stage ${RELEASE_STAGE}"
popd
