#!/bin/bash

set -e

cd diego-release/

export GOPATH=$PWD
export PATH=$GOPATH/bin:$PATH

cd src/github.com/pivotal-cf-experimental/vizzini/

go install github.com/onsi/ginkgo/ginkgo

ginkgo \
  -nodes=4 \
  -skip="{LOCAL}" \
  -randomizeAllSpecs \
  "$@" \
  -- \
  --receptor-address=${RECEPTOR_ADDRESS} \
  --routable-domain-suffix=${ROUTABLE_DOMAIN_SUFFIX}
