#!/bin/bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SCRIPTS_DIR="$(realpath ${SCRIPTS_DIR}/..)"
. "${SCRIPTS_DIR}/get_paths.sh"

BIN_DIR="${DIEGO_RELEASE_DIR}/bin"
mkdir -p "${BIN_DIR}"
export PATH="${PATH}:${BIN_DIR}"
export GOFLAGS="-buildvcs=false"

set -e
pushd "${DIEGO_RELEASE_DIR}/src/code.cloudfoundry.org"
  go build -o "$BIN_DIR/nats-server" github.com/nats-io/nats-server/v2
popd
set +e

echo "CONTAINER DEBUG INFO"
echo "SCRIPTS_DIR = ${SCRIPTS_DIR}"
echo "DIEGO_RELEASE_DIR = ${DIEGO_RELEASE_DIR}"
echo "PATH = ${PATH}"

ERROR_CODE=0

SQL_FLAVOR=mysql ${SCRIPTS_DIR}/ci/run-unit-tests-with-backing-store
ERROR_CODE=$?

SQL_FLAVOR=postgres ${SCRIPTS_DIR}/ci/run-unit-tests-with-backing-store
let ERROR_CODE+=$?

${SCRIPTS_DIR}/ci/run-unit-tests-no-backing-store
let ERROR_CODE+=$?

if [ ${ERROR_CODE} -eq 0 ]; then
  echo "Diego Unit Tests Passed."
else
  echo "Diego Unit Tests Failed!"
fi

exit ${ERROR_CODE}
