#!/bin/bash
# vim: set ft=sh

set -e

function initialize_mysql {
    cat << EOF > /etc/my.cnf
[mysqld]
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
EOF
    $datadir=/mysql-datadir
    mkdir $datadir
    mount -t tmpfs -o size=2g tmpfs $datadir
    rsync -av --progress /var/lib/mysql/ $datadir
    sed -i /etc/mysql/mysql.conf.d/mysqld.conf "s/datadir.*/datadir=$datadir"
}

if [ "${SQL_FLAVOR}" = "mysql" ]; then
  initialize_mysql
  service mysql start
elif [ "${SQL_FLAVOR}" = "postgres" ]; then
  service postgresql start
else
  initialize_mysql
  service mysql start
  service postgresql start
fi


./diego-release/scripts/ci/run_unit_internal
