#!/bin/bash

set -e -x -u

acceptance_tests_manifest=${PWD}/${ACCEPTANCE_TESTS_MANIFEST}

./diego-release/scripts/ci/bosh_setup

# Report which cf-release and diego-release SHAs were deployed together
# for this run of the DATS
bosh deployments
bosh releases

bosh deployment ${acceptance_tests_manifest}
bosh -n deploy
bosh run errand diego_acceptance_tests --keep-alive
