#!/bin/bash
# vim: set ft=sh

set -e

echo "run_unit_internal SQL " + ${RUN_SQL_TESTS}

cd diego-release/

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

SCRIPT=${SCRIPT:-run-unit-tests}

go install github.com/apcera/gnatsd
go install github.com/coreos/etcd
go install github.com/onsi/ginkgo/ginkgo

"scripts/${SCRIPT}" "$@"
