#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

rm -rf diego-release/deployments-runtime || true
cp -R deployments-runtime diego-release/

pushd diego-release
  ./scripts/ci/create_drone_yml scripts/ci/run_diego_cats.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd
