#!/bin/bash

# always use mysql (this isn't configurable atm)
export SQL_FLAVOR=mysql

dir=$(dirname $0)
source $dir/setup_inigo

set -exo pipefail

export DEFAULT_EVENTUALLY_TIMEOUT=60s

pushd "${GOPATH_ROOT}/src/code.cloudfoundry.org/diego-upgrade-stability-tests"
  ginkgo -failFast -failOnPending -randomizeAllSpecs -trace -race -slowSpecThreshold=60 -keepGoing $@
popd
