#!/bin/bash

set -e -x

docker run -a stdout -a stderr -w /root/workspace \
  -v $PWD:/root/workspace \
  -e GOROOT=/usr/local/go \
  -e BOSH_PASSWORD \
  -e BOSH_TARGET \
  -e BOSH_USER \
  -e DATADOG_API_KEY \
  -e DEPLOYMENTS_DIR \
  -e DEPLOYMENT_TAG \
  -e SMOKE_TESTS_MANIFEST \
  cloudfoundry/diego-pipeline \
  /bin/bash -l diego-release/scripts/ci/run_diego_smoke_tests_inner

