#!/bin/bash

dir=$(dirname $0)
source $dir/setup_inigo

set -e -x

pushd "${GOPATH_ROOT}/src/code.cloudfoundry.org/diego-upgrade-stability-tests/collocated"
  ginkgo -failOnPending -randomizeAllSpecs -trace -race -slowSpecThreshold=60 -keepGoing $@
popd
