#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

./diego-release/scripts/ci/create_drone_yml diego-release/scripts/ci/run_nondiego_cats.drone.yml .drone.yml

/var/vcap/packages/drone/bin/drone -v -privileged build
