#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone
export PATH=/var/vcap/packages/drone/bin:$PATH

./diego-release/scripts/ci/create_drone_yml \
  ./diego-release/scripts/ci/run_inigo.drone.yml \
  .drone.yml

drone -v -privileged build
