#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

pushd diego-release
  ./scripts/create_drone_yml scripts/ci/run_diego_smoke_tests.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd
