#!/bin/bash

set -e -x -u

RELEASE_ROOT=$(dirname $(dirname $0))

TMPDIR=${TMPDIR:-/tmp}

rm -rf ${TMPDIR}/diego-release-gopath.*

export GOPATH_ROOT=$(mktemp -d ${TMPDIR}/diego-release-gopath.XXXXX)

export GOPATH=$GOPATH_ROOT
export PATH=$GOPATH_ROOT/bin:$PATH

function copy_to_gopath {
  mkdir -p ${GOPATH_ROOT}/src/$(dirname $1)
  rsync -a src/$(basename $1)/ ${GOPATH_ROOT}/src/$1/
}

# grab and set up our components
for package in \
    github.com/cloudfoundry-incubator/inigo \
    github.com/cloudfoundry-incubator/auctioneer \
    github.com/cloudfoundry-incubator/executor \
    github.com/cloudfoundry-incubator/route-emitter \
    github.com/cloudfoundry-incubator/converger \
    github.com/cloudfoundry-incubator/rep \
    github.com/cloudfoundry-incubator/stager \
    github.com/cloudfoundry-incubator/linux-circus \
    github.com/cloudfoundry-incubator/tps \
    github.com/cloudfoundry-incubator/nsync \
    github.com/cloudfoundry-incubator/file-server \
    github.com/cloudfoundry-incubator/warden-linux;
    do
  copy_to_gopath $package
done

# install application dependencies
go get github.com/coreos/etcd
go install github.com/coreos/etcd
go get github.com/apcera/gnatsd
go install github.com/apcera/gnatsd

# grab master of gorouter
go get -d github.com/cloudfoundry/gorouter
export ROUTER_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry/gorouter/Godeps/_workspace:${GOPATH_ROOT}

# set up inigo's own dependencies
export GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/inigo/Godeps/_workspace:${GOPATH}
export PATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/inigo/Godeps/_workspace/bin:${PATH}

# set up compile-time $GOPATHs for each component
export LOGGREGATOR_GOPATH=${GOPATH_ROOT}/loggregator
export ROUTER_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry/gorouter/Godeps/_workspace
export AUCTIONEER_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/auctioneer/Godeps/_workspace
export CONVERGER_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/converger/Godeps/_workspace
export EXECUTOR_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/executor/Godeps/_workspace
export FILE_SERVER_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/file-server/Godeps/_workspace
export LINUX_CIRCUS_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/linux-circus/Godeps/_workspace
export DOCKER_CIRCUS_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/docker-circus/Godeps/_workspace
export NSYNC_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/nsync/Godeps/_workspace
export REP_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/rep/Godeps/_workspace
export ROUTE_EMITTER_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/route-emitter/Godeps/_workspace
export STAGER_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/stager/Godeps/_workspace
export TPS_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/tps/Godeps/_workspace
export WARDEN_LINUX_GOPATH=${GOPATH_ROOT}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/warden-linux/Godeps/_workspace

# grab master of loggregator
git clone https://github.com/cloudfoundry/loggregator $LOGGREGATOR_GOPATH --depth 1

pushd $LOGGREGATOR_GOPATH
  git submodule update --init --recursive
popd

cd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/inigo

./scripts/drone-test
