#!/bin/bash

set -e -x -u

smoke_tests_manifest="${PWD}/${SMOKE_TESTS_MANIFEST}"

$(dirname $0)/bosh_setup

bosh deployment ${smoke_tests_manifest}
bosh -n deploy
bosh run errand diego_smoke_tests --keep-alive
