#!/bin/bash

set -e -x -u

acceptance_tests_manifest=${PWD}/${ACCEPTANCE_TESTS_MANIFEST}

eval $(./diego-release/scripts/ci/bosh_config)
./diego-release/scripts/ci/bosh_setup

bosh deployment ${acceptance_tests_manifest}
bosh -n deploy
bosh run errand diego_acceptance_tests --keep-alive
