#!/bin/bash

set -e -x -u

smoke_tests_manifest=${PWD}/${SMOKE_TESTS_MANIFEST}

eval $(./scripts/ci/bosh_config)
./scripts/ci/bosh_setup

bosh deployment ${smoke_tests_manifest}
bosh -n deploy
(
  bosh run errand diego_smoke_tests
)
smoke_tests_status=$?

if [[ $smoke_tests_status -eq 0 ]]
then
  smoke_tests_metric=1
else
  smoke_tests_metric=0
fi

./scripts/ci/emit-datadog-smoke-test-metric $smoke_tests_metric ${DEPLOYMENT_TAG}

exit $smoke_tests_status
