#!/bin/bash

set -e -x

export GOROOT=/usr/local/go
export GOPATH_ROOT=$PWD
export GOPATH=:${GOPATH_ROOT}

export PATH=${GOPATH_ROOT}/bin:${GOROOT}/bin:${PATH}

export ROUTER_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry/gorouter/Godeps/_workspace:${GOPATH_ROOT}
export LOGGREGATOR_GOPATH=${GOPATH_ROOT}/loggregator
export AUCTIONEER_GOPATH=${GOPATH_ROOT}
export CONVERGER_GOPATH=${GOPATH_ROOT}
export EXECUTOR_GOPATH=${GOPATH_ROOT}
export FILE_SERVER_GOPATH=${GOPATH_ROOT}
export LINUX_CIRCUS_GOPATH=${GOPATH_ROOT}
export DOCKER_CIRCUS_GOPATH=${GOPATH_ROOT}
export NSYNC_GOPATH=${GOPATH_ROOT}
export REP_GOPATH=${GOPATH_ROOT}
export ROUTE_EMITTER_GOPATH=${GOPATH_ROOT}
export STAGER_GOPATH=${GOPATH_ROOT}
export TPS_GOPATH=${GOPATH_ROOT}
export WARDEN_LINUX_GOPATH=${GOPATH_ROOT}

# install application dependencies
for package in github.com/coreos/etcd github.com/apcera/gnatsd; do
  go install $package
done

cd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/inigo

./scripts/drone-test
