#!/bin/bash

set -e -x -u

eval $(./scripts/ci/bosh_config)
./scripts/bosh_setup

bosh download manifest cf-$DEPLOYMENT_NAME cf-deployment.yml
bosh deployment cf-deployment.yml
bosh run errand acceptance_tests
