#!/bin/bash
# vim: set ft=sh

set -e

cd diego-release

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/nats-io/nats-server
go install github.com/onsi/ginkgo/ginkgo

cd src/code.cloudfoundry.org/auction/simulation

# Tee output to a log file but exclude component/test logs from stdout so
# concourse output is not overloaded
ginkgo -r -p -v | tee simulation-output.log | grep -v '{"timestamp"'
ERROR_CODE=$?

if [ ${ERROR_CODE} -eq 0 ]; then
  echo "Auction simulation completed."
else
  echo "Auction simulation failed!"
fi

exit ${ERROR_CODE}
