#!/bin/bash

set -e -x -u

build_name=$1
build_counter=$2

curl -H "Content-type: application/json" -X POST \
    -d "{
      \"service_key\": \"${PAGER_DUTY_SERVICE_KEY}\",
      \"incident_key\": \"${build_name}-${build_counter}-failed\",
      \"event_type\": \"trigger\",
      \"description\": \"FAILURE for ${build_name} #${build_counter}\"
    }" \
    "https://events.pagerduty.com/generic/2010-04-15/create_event.json"
