#!/bin/bash

set -e -x

export DRONE_TMP=$TMPDIR/drone

rm -f diego-release/light-bosh-stemcell-latest-aws-xen-ubuntu-trusty-go_agent.tgz
cp light-bosh-stemcell-latest-aws-xen-ubuntu-trusty-go_agent.tgz diego-release/

pushd diego-release
  ./scripts/ci/create_drone_yml scripts/ci/upload_stemcell.drone.yml .drone.yml
  /var/vcap/packages/drone/bin/drone -v -privileged build
popd
