---
director_uuid: (( config_from_cf.cf_director_uuid ))

name: (( config_from_cf.cf_deployment_name "-diego-acceptance-tests" ))

releases:
- name: diego
  version: latest 
networks:
- name: diego-acceptance-tests
  type: manual
  subnets: (( iaas_settings.subnet_configs.diego-acceptance-tests.subnets ))
resource_pools:
- name: errand
  network: diego-acceptance-tests
  stemcell: (( iaas_settings.stemcell ))
  cloud_properties: (( iaas_settings.resource_pool_cloud_properties.errand.cloud_properties ))
compilation:
  network: diego-acceptance-tests
  reuse_compilation_vms: true
  workers: 1
  cloud_properties: (( iaas_settings.compilation_cloud_properties ))
update:
  canaries: 1
  canary_watch_time: 5000-120000
  update_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
jobs:
- name: diego_acceptance_tests
  templates:
  - name: acceptance-tests
    release: diego
  lifecycle: errand
  instances: 1
  networks:
  - name: diego-acceptance-tests
  resource_pool: errand
properties:
  acceptance_tests:
    api: (( acceptance_tests_properties.api ))
    apps_domain: (( acceptance_tests_properties.apps_domain ))
    admin_user: (( acceptance_tests_properties.admin_user ))
    admin_password: (( acceptance_tests_properties.admin_password ))
    secure_address: (( acceptance_tests_properties.secure_address ))
    skip_ssl_validation: (( acceptance_tests_properties.skip_cert_verify ))
    skip_dea_validation: (( acceptance_tests_properties.skip_dea_compatibility ))

# The keys below should not be included in the final stub
config_from_cf: (( merge ))
iaas_settings: (( merge ))
acceptance_tests_properties: (( merge ))
