// Code generated by counterfeiter. DO NOT EDIT.
package repfakes

import (
	"net/http"
	"sync"
	"time"

	"code.cloudfoundry.org/bbs/models"
	lager "code.cloudfoundry.org/lager/v3"
)

type FakeClient struct {
	CancelTaskStub        func(lager.Logger, string) error
	cancelTaskMutex       sync.RWMutex
	cancelTaskArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
	}
	cancelTaskReturns struct {
		result1 error
	}
	cancelTaskReturnsOnCall map[int]struct {
		result1 error
	}
	PerformStub        func(lager.Logger, models.Work) (models.Work, error)
	performMutex       sync.RWMutex
	performArgsForCall []struct {
		arg1 lager.Logger
		arg2 models.Work
	}
	performReturns struct {
		result1 models.Work
		result2 error
	}
	performReturnsOnCall map[int]struct {
		result1 models.Work
		result2 error
	}
	SetStateClientStub        func(*http.Client)
	setStateClientMutex       sync.RWMutex
	setStateClientArgsForCall []struct {
		arg1 *http.Client
	}
	StateStub        func(lager.Logger) (models.CellState, error)
	stateMutex       sync.RWMutex
	stateArgsForCall []struct {
		arg1 lager.Logger
	}
	stateReturns struct {
		result1 models.CellState
		result2 error
	}
	stateReturnsOnCall map[int]struct {
		result1 models.CellState
		result2 error
	}
	StateClientTimeoutStub        func() time.Duration
	stateClientTimeoutMutex       sync.RWMutex
	stateClientTimeoutArgsForCall []struct {
	}
	stateClientTimeoutReturns struct {
		result1 time.Duration
	}
	stateClientTimeoutReturnsOnCall map[int]struct {
		result1 time.Duration
	}
	StopLRPInstanceStub        func(lager.Logger, models.ActualLRPKey, models.ActualLRPInstanceKey) error
	stopLRPInstanceMutex       sync.RWMutex
	stopLRPInstanceArgsForCall []struct {
		arg1 lager.Logger
		arg2 models.ActualLRPKey
		arg3 models.ActualLRPInstanceKey
	}
	stopLRPInstanceReturns struct {
		result1 error
	}
	stopLRPInstanceReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateLRPInstanceStub        func(lager.Logger, models.LRPUpdate) error
	updateLRPInstanceMutex       sync.RWMutex
	updateLRPInstanceArgsForCall []struct {
		arg1 lager.Logger
		arg2 models.LRPUpdate
	}
	updateLRPInstanceReturns struct {
		result1 error
	}
	updateLRPInstanceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) CancelTask(arg1 lager.Logger, arg2 string) error {
	fake.cancelTaskMutex.Lock()
	ret, specificReturn := fake.cancelTaskReturnsOnCall[len(fake.cancelTaskArgsForCall)]
	fake.cancelTaskArgsForCall = append(fake.cancelTaskArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
	}{arg1, arg2})
	stub := fake.CancelTaskStub
	fakeReturns := fake.cancelTaskReturns
	fake.recordInvocation("CancelTask", []interface{}{arg1, arg2})
	fake.cancelTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) CancelTaskCallCount() int {
	fake.cancelTaskMutex.RLock()
	defer fake.cancelTaskMutex.RUnlock()
	return len(fake.cancelTaskArgsForCall)
}

func (fake *FakeClient) CancelTaskCalls(stub func(lager.Logger, string) error) {
	fake.cancelTaskMutex.Lock()
	defer fake.cancelTaskMutex.Unlock()
	fake.CancelTaskStub = stub
}

func (fake *FakeClient) CancelTaskArgsForCall(i int) (lager.Logger, string) {
	fake.cancelTaskMutex.RLock()
	defer fake.cancelTaskMutex.RUnlock()
	argsForCall := fake.cancelTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) CancelTaskReturns(result1 error) {
	fake.cancelTaskMutex.Lock()
	defer fake.cancelTaskMutex.Unlock()
	fake.CancelTaskStub = nil
	fake.cancelTaskReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) CancelTaskReturnsOnCall(i int, result1 error) {
	fake.cancelTaskMutex.Lock()
	defer fake.cancelTaskMutex.Unlock()
	fake.CancelTaskStub = nil
	if fake.cancelTaskReturnsOnCall == nil {
		fake.cancelTaskReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cancelTaskReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Perform(arg1 lager.Logger, arg2 models.Work) (models.Work, error) {
	fake.performMutex.Lock()
	ret, specificReturn := fake.performReturnsOnCall[len(fake.performArgsForCall)]
	fake.performArgsForCall = append(fake.performArgsForCall, struct {
		arg1 lager.Logger
		arg2 models.Work
	}{arg1, arg2})
	stub := fake.PerformStub
	fakeReturns := fake.performReturns
	fake.recordInvocation("Perform", []interface{}{arg1, arg2})
	fake.performMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) PerformCallCount() int {
	fake.performMutex.RLock()
	defer fake.performMutex.RUnlock()
	return len(fake.performArgsForCall)
}

func (fake *FakeClient) PerformCalls(stub func(lager.Logger, models.Work) (models.Work, error)) {
	fake.performMutex.Lock()
	defer fake.performMutex.Unlock()
	fake.PerformStub = stub
}

func (fake *FakeClient) PerformArgsForCall(i int) (lager.Logger, models.Work) {
	fake.performMutex.RLock()
	defer fake.performMutex.RUnlock()
	argsForCall := fake.performArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) PerformReturns(result1 models.Work, result2 error) {
	fake.performMutex.Lock()
	defer fake.performMutex.Unlock()
	fake.PerformStub = nil
	fake.performReturns = struct {
		result1 models.Work
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) PerformReturnsOnCall(i int, result1 models.Work, result2 error) {
	fake.performMutex.Lock()
	defer fake.performMutex.Unlock()
	fake.PerformStub = nil
	if fake.performReturnsOnCall == nil {
		fake.performReturnsOnCall = make(map[int]struct {
			result1 models.Work
			result2 error
		})
	}
	fake.performReturnsOnCall[i] = struct {
		result1 models.Work
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) SetStateClient(arg1 *http.Client) {
	fake.setStateClientMutex.Lock()
	fake.setStateClientArgsForCall = append(fake.setStateClientArgsForCall, struct {
		arg1 *http.Client
	}{arg1})
	stub := fake.SetStateClientStub
	fake.recordInvocation("SetStateClient", []interface{}{arg1})
	fake.setStateClientMutex.Unlock()
	if stub != nil {
		fake.SetStateClientStub(arg1)
	}
}

func (fake *FakeClient) SetStateClientCallCount() int {
	fake.setStateClientMutex.RLock()
	defer fake.setStateClientMutex.RUnlock()
	return len(fake.setStateClientArgsForCall)
}

func (fake *FakeClient) SetStateClientCalls(stub func(*http.Client)) {
	fake.setStateClientMutex.Lock()
	defer fake.setStateClientMutex.Unlock()
	fake.SetStateClientStub = stub
}

func (fake *FakeClient) SetStateClientArgsForCall(i int) *http.Client {
	fake.setStateClientMutex.RLock()
	defer fake.setStateClientMutex.RUnlock()
	argsForCall := fake.setStateClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) State(arg1 lager.Logger) (models.CellState, error) {
	fake.stateMutex.Lock()
	ret, specificReturn := fake.stateReturnsOnCall[len(fake.stateArgsForCall)]
	fake.stateArgsForCall = append(fake.stateArgsForCall, struct {
		arg1 lager.Logger
	}{arg1})
	stub := fake.StateStub
	fakeReturns := fake.stateReturns
	fake.recordInvocation("State", []interface{}{arg1})
	fake.stateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) StateCallCount() int {
	fake.stateMutex.RLock()
	defer fake.stateMutex.RUnlock()
	return len(fake.stateArgsForCall)
}

func (fake *FakeClient) StateCalls(stub func(lager.Logger) (models.CellState, error)) {
	fake.stateMutex.Lock()
	defer fake.stateMutex.Unlock()
	fake.StateStub = stub
}

func (fake *FakeClient) StateArgsForCall(i int) lager.Logger {
	fake.stateMutex.RLock()
	defer fake.stateMutex.RUnlock()
	argsForCall := fake.stateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) StateReturns(result1 models.CellState, result2 error) {
	fake.stateMutex.Lock()
	defer fake.stateMutex.Unlock()
	fake.StateStub = nil
	fake.stateReturns = struct {
		result1 models.CellState
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) StateReturnsOnCall(i int, result1 models.CellState, result2 error) {
	fake.stateMutex.Lock()
	defer fake.stateMutex.Unlock()
	fake.StateStub = nil
	if fake.stateReturnsOnCall == nil {
		fake.stateReturnsOnCall = make(map[int]struct {
			result1 models.CellState
			result2 error
		})
	}
	fake.stateReturnsOnCall[i] = struct {
		result1 models.CellState
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) StateClientTimeout() time.Duration {
	fake.stateClientTimeoutMutex.Lock()
	ret, specificReturn := fake.stateClientTimeoutReturnsOnCall[len(fake.stateClientTimeoutArgsForCall)]
	fake.stateClientTimeoutArgsForCall = append(fake.stateClientTimeoutArgsForCall, struct {
	}{})
	stub := fake.StateClientTimeoutStub
	fakeReturns := fake.stateClientTimeoutReturns
	fake.recordInvocation("StateClientTimeout", []interface{}{})
	fake.stateClientTimeoutMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) StateClientTimeoutCallCount() int {
	fake.stateClientTimeoutMutex.RLock()
	defer fake.stateClientTimeoutMutex.RUnlock()
	return len(fake.stateClientTimeoutArgsForCall)
}

func (fake *FakeClient) StateClientTimeoutCalls(stub func() time.Duration) {
	fake.stateClientTimeoutMutex.Lock()
	defer fake.stateClientTimeoutMutex.Unlock()
	fake.StateClientTimeoutStub = stub
}

func (fake *FakeClient) StateClientTimeoutReturns(result1 time.Duration) {
	fake.stateClientTimeoutMutex.Lock()
	defer fake.stateClientTimeoutMutex.Unlock()
	fake.StateClientTimeoutStub = nil
	fake.stateClientTimeoutReturns = struct {
		result1 time.Duration
	}{result1}
}

func (fake *FakeClient) StateClientTimeoutReturnsOnCall(i int, result1 time.Duration) {
	fake.stateClientTimeoutMutex.Lock()
	defer fake.stateClientTimeoutMutex.Unlock()
	fake.StateClientTimeoutStub = nil
	if fake.stateClientTimeoutReturnsOnCall == nil {
		fake.stateClientTimeoutReturnsOnCall = make(map[int]struct {
			result1 time.Duration
		})
	}
	fake.stateClientTimeoutReturnsOnCall[i] = struct {
		result1 time.Duration
	}{result1}
}

func (fake *FakeClient) StopLRPInstance(arg1 lager.Logger, arg2 models.ActualLRPKey, arg3 models.ActualLRPInstanceKey) error {
	fake.stopLRPInstanceMutex.Lock()
	ret, specificReturn := fake.stopLRPInstanceReturnsOnCall[len(fake.stopLRPInstanceArgsForCall)]
	fake.stopLRPInstanceArgsForCall = append(fake.stopLRPInstanceArgsForCall, struct {
		arg1 lager.Logger
		arg2 models.ActualLRPKey
		arg3 models.ActualLRPInstanceKey
	}{arg1, arg2, arg3})
	stub := fake.StopLRPInstanceStub
	fakeReturns := fake.stopLRPInstanceReturns
	fake.recordInvocation("StopLRPInstance", []interface{}{arg1, arg2, arg3})
	fake.stopLRPInstanceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) StopLRPInstanceCallCount() int {
	fake.stopLRPInstanceMutex.RLock()
	defer fake.stopLRPInstanceMutex.RUnlock()
	return len(fake.stopLRPInstanceArgsForCall)
}

func (fake *FakeClient) StopLRPInstanceCalls(stub func(lager.Logger, models.ActualLRPKey, models.ActualLRPInstanceKey) error) {
	fake.stopLRPInstanceMutex.Lock()
	defer fake.stopLRPInstanceMutex.Unlock()
	fake.StopLRPInstanceStub = stub
}

func (fake *FakeClient) StopLRPInstanceArgsForCall(i int) (lager.Logger, models.ActualLRPKey, models.ActualLRPInstanceKey) {
	fake.stopLRPInstanceMutex.RLock()
	defer fake.stopLRPInstanceMutex.RUnlock()
	argsForCall := fake.stopLRPInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) StopLRPInstanceReturns(result1 error) {
	fake.stopLRPInstanceMutex.Lock()
	defer fake.stopLRPInstanceMutex.Unlock()
	fake.StopLRPInstanceStub = nil
	fake.stopLRPInstanceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) StopLRPInstanceReturnsOnCall(i int, result1 error) {
	fake.stopLRPInstanceMutex.Lock()
	defer fake.stopLRPInstanceMutex.Unlock()
	fake.StopLRPInstanceStub = nil
	if fake.stopLRPInstanceReturnsOnCall == nil {
		fake.stopLRPInstanceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.stopLRPInstanceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) UpdateLRPInstance(arg1 lager.Logger, arg2 models.LRPUpdate) error {
	fake.updateLRPInstanceMutex.Lock()
	ret, specificReturn := fake.updateLRPInstanceReturnsOnCall[len(fake.updateLRPInstanceArgsForCall)]
	fake.updateLRPInstanceArgsForCall = append(fake.updateLRPInstanceArgsForCall, struct {
		arg1 lager.Logger
		arg2 models.LRPUpdate
	}{arg1, arg2})
	stub := fake.UpdateLRPInstanceStub
	fakeReturns := fake.updateLRPInstanceReturns
	fake.recordInvocation("UpdateLRPInstance", []interface{}{arg1, arg2})
	fake.updateLRPInstanceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) UpdateLRPInstanceCallCount() int {
	fake.updateLRPInstanceMutex.RLock()
	defer fake.updateLRPInstanceMutex.RUnlock()
	return len(fake.updateLRPInstanceArgsForCall)
}

func (fake *FakeClient) UpdateLRPInstanceCalls(stub func(lager.Logger, models.LRPUpdate) error) {
	fake.updateLRPInstanceMutex.Lock()
	defer fake.updateLRPInstanceMutex.Unlock()
	fake.UpdateLRPInstanceStub = stub
}

func (fake *FakeClient) UpdateLRPInstanceArgsForCall(i int) (lager.Logger, models.LRPUpdate) {
	fake.updateLRPInstanceMutex.RLock()
	defer fake.updateLRPInstanceMutex.RUnlock()
	argsForCall := fake.updateLRPInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) UpdateLRPInstanceReturns(result1 error) {
	fake.updateLRPInstanceMutex.Lock()
	defer fake.updateLRPInstanceMutex.Unlock()
	fake.UpdateLRPInstanceStub = nil
	fake.updateLRPInstanceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) UpdateLRPInstanceReturnsOnCall(i int, result1 error) {
	fake.updateLRPInstanceMutex.Lock()
	defer fake.updateLRPInstanceMutex.Unlock()
	fake.UpdateLRPInstanceStub = nil
	if fake.updateLRPInstanceReturnsOnCall == nil {
		fake.updateLRPInstanceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateLRPInstanceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cancelTaskMutex.RLock()
	defer fake.cancelTaskMutex.RUnlock()
	fake.performMutex.RLock()
	defer fake.performMutex.RUnlock()
	fake.setStateClientMutex.RLock()
	defer fake.setStateClientMutex.RUnlock()
	fake.stateMutex.RLock()
	defer fake.stateMutex.RUnlock()
	fake.stateClientTimeoutMutex.RLock()
	defer fake.stateClientTimeoutMutex.RUnlock()
	fake.stopLRPInstanceMutex.RLock()
	defer fake.stopLRPInstanceMutex.RUnlock()
	fake.updateLRPInstanceMutex.RLock()
	defer fake.updateLRPInstanceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ models.RepClient = new(FakeClient)
