#!/bin/bash -lxe

git submodule update --init --recursive

if ! which hg >/dev/null 2>&1; then
  echo "mercurial is not installed; aborting"
  exit 1
fi

cd src/diego

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go get -u github.com/vito/gocart
gocart

# grab warden submodule
cd src/github.com/pivotal-cf-experimental/garden
git submodule update --init --recursive
