name: diego-acceptance-tests

director_uuid: <%= `bosh status --uuid` %>

releases:
  - name: diego
    version: latest

networks:
- name: acceptance-tests
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.20.8/30
    reserved:
    - 10.244.20.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.20.12/30
    reserved:
    - 10.244.20.13
    static: []

resource_pools:
  - name: acceptance-tests
    network: acceptance-tests
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  cloud_properties:
    name: random
  network: acceptance-tests
  reuse_compilation_vms: true
  workers: 6

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

jobs:
- name: diego_acceptance_tests
  templates:
    - name: acceptance-tests
      release: diego
  lifecycle: errand
  instances: 1
  networks:
    - name: acceptance-tests
  resource_pool: acceptance-tests

properties:
  acceptance_tests:
    api:  api.10.244.0.34.xip.io
    apps_domain: 10.244.0.34.xip.io
    admin_user: admin
    admin_password: admin
    secure_address: 10.244.16.2:4001
    skip_ssl_validation: true
