meta: (( merge ))

networks: (( merge ))

releases:
  - name: diego
    version: latest

external_services: (( merge ))

jobs:
  - name: executor_z1
    release: diego
    templates:
      - name: executor
        release: diego
      - name: converger
        release: diego
      - name: rep
        release: diego
      - name: auctioneer
        release: diego
      - name: warden
        release: diego
    instances: 1
    resource_pool: large_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      loggregator_endpoint: (( external_services.loggregator_endpoint.z1 ))

  - name: executor_z2
    release: diego
    templates:
      - name: executor
        release: diego
      - name: converger
        release: diego
      - name: rep
        release: diego
      - name: auctioneer
        release: diego
      - name: warden
        release: diego
    instances: 1
    resource_pool: large_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      loggregator_endpoint: (( external_services.loggregator_endpoint.z2 ))

  - name: file_server_z1
    release: diego
    templates:
      - name: file_server
        release: diego
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      cc: (( external_services.cc ))


  - name: file_server_z2
    release: diego
    templates:
      - name: file_server
        release: diego
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      cc: (( external_services.cc ))

  - name: stager_z1
    release: diego
    templates:
      - name: stager
        release: diego
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      nats: (( external_services.nats ))

  - name: stager_z2
    release: diego
    templates:
      - name: stager
        release: diego
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      nats: (( external_services.nats ))

  - name: app_manager_z1
    release: diego
    templates:
      - name: app-manager
        release: diego
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      nats: (( external_services.nats ))

  - name: app_manager_z2
    release: diego
    templates:
      - name: app-manager
        release: diego
    instances: 1
    resource_pool: small_z2
    networks:
      - name: diego2
    properties:
      network_name: diego2
      nats: (( external_services.nats ))

  - name: runtime_metrics_server_z1
    release: diego
    templates:
      - name: runtime_metrics_server
        release: diego
    instances: 1
    resource_pool: small_z1
    networks:
      - name: diego1
    properties:
      network_name: diego1
      nats: (( external_services.nats ))

  - name: etcd_z1
    release: diego
    templates:
      - name: etcd
        release: diego
      - name: etcd_metrics_server
        release: diego
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( merge ))
    properties:
      network_name: diego1
    update:
      serial: true

  - name: etcd_z2
    release: diego
    templates:
      - name: etcd
        release: diego
      - name: etcd_metrics_server
        release: diego
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( merge ))
    properties:
      network_name: diego2
    update:
      serial: true

  - name: etcd_z3
    release: diego
    templates:
      - name: etcd
        release: diego
      - name: etcd_metrics_server
        release: diego
    instances: 1
    resource_pool: medium_z3
    networks:
      - name: diego3
        static_ips: (( merge ))
    properties:
      network_name: diego3
    update:
      serial: true

properties:
  ssl:
    skip_cert_verify: false

  warden: ~

  executor:
    warden: ~

  syslog_aggregator: ~

  rep:
    etcd:
      machines: (( .properties.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  auctioneer:
    etcd:
      machines: (( .properties.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  etcd:
    machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))

  etcd_metrics_server:
    job_name: "etcd-diego"
    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))

  runtime_metrics_server:
    etcd:
      machines: (( .properties.etcd.machines ))

    nats:
      machines: (( external_services.nats.machines ))
      username: (( external_services.nats.user ))
      password: (( external_services.nats.password ))
