#!/bin/bash

set -e -x -u

chruby 2.0

WORKING_DIR=`pwd`

pushd cf-release
  ./update
  echo cf | bosh create release --with-tarball
  mv dev_releases/*.tgz "${WORKING_DIR}/cf-release-created-by-ci.tgz"
popd


pushd diego-release
  echo diego | bosh create release --force
  mv dev_releases/*.tgz "${WORKING_DIR}/diego-release-created-by-ci.tgz"
popd
