#!/bin/bash

set -e -x -u

mkdir -p "output"
OUTPUT_DIR="$PWD/output"

pushd cf-release
  echo cf | bosh create release --with-tarball
  mv dev_releases/*.tgz "${OUTPUT_DIR}/cf-release-created-by-ci.tgz"
popd


echo diego | bosh create release --force
mv dev_releases/*.tgz "${OUTPUT_DIR}/diego-release-created-by-ci.tgz"

