#!/bin/bash

set -e -x -u

mkdir -p "output"
OUTPUT_DIR="$PWD/output"

echo "----- Clean drone.yml files"
git checkout -- .drone.yml

echo "----- Bring master up to date"
git checkout master
git merge develop --ff-only

ssh-add tmp/github
rm tmp/github

./scripts/update

echo "----- Create final release"
bosh -n create release --final --with-tarball

echo "----- Move tarball to ${OUTPUT_DIR} for artifact publishing"
mv releases/*.tgz "${OUTPUT_DIR}/diego-final-release-created-by-ci.tgz"

echo "----- Update master and develop branches on origin"
git commit -Am "CREATE FINAL RELEASE (automated commit)"

echo "----- Merge master back into develop"
git checkout develop
git pull origin/develop --ff-only
git merge -m "Merge branch 'master' into develop (automated commit)"

echo "----- Push changes"
git push origin develop
git push origin master
