#!/bin/bash

set -e -x -u

mkdir -p "output"
OUTPUT_DIR="$PWD/output"

echo "----- Clean drone.yml files"
git checkout -- .drone.yml

echo "----- Bring master up to date"
git checkout master
git merge develop --ff-only

echo "----- Configure git to use our ssh key"
export GIT_SSH=$(pwd)/tmp/git_ssh.sh
chmod 600 $(pwd)/tmp/github
echo "ssh -i $(pwd)/tmp/github" '"$@"' > $GIT_SSH
chmod +x $GIT_SSH

./scripts/update

echo "----- Create dev release" # to work around https://www.pivotaltracker.com/story/show/74823266
bosh -n create release

echo "----- Create final release"
bosh -n create release --final --with-tarball

echo "----- Move tarball to ${OUTPUT_DIR} for artifact publishing"
mv releases/*.tgz "${OUTPUT_DIR}/diego-final-release-created-by-ci.tgz"

echo "----- Set git identity"
git config user.email "cf-diego@pivotallabs.com"
git config user.name "CI (Automated)"

echo "----- Update master and develop branches on origin"
git commit -am "CREATE FINAL RELEASE (automated commit)"

echo "----- Merge master back into develop"
git checkout develop
git pull --ff-only origin develop
git merge -m "Merge branch 'master' into develop (automated commit)" master

echo "----- Push changes"
git push origin develop
git push origin master
