#!/bin/bash

set -e -x

git submodule update --init --recursive

bosh target ${BOSH_TARGET}

if [ ! -d /tmp/cache/cf-release ]; then
  git clone https://github.com/cloudfoundry/cf-release.git /tmp/cache/cf-release
fi

git clone $DEPLOYMENTS_REPO /tmp/deployments

pushd /tmp/cache/cf-release
  git checkout develop

  git pull --ff-only origin develop
  git submodule foreach --recursive git submodule sync
  git submodule update --init --recursive

  git reset --hard
  git clean --force --force -d
  git submodule foreach --recursive git clean --force --force -d

  # work around uaa prepackaging :(
  rm src/uaa/.git
  ln -s $PWD/.git/modules/src/uaa/.git src/uaa/.git

  echo cf | bosh create release
  bosh -n upload release --rebase --skip-if-exists || true
popd

echo diego | bosh create release
bosh -n upload release --rebase --skip-if-exists || true

./generate_combo_manifest aws /tmp/cache/cf-release \
  /tmp/deployments/$DEPLOYMENT_NAME/stubs/* > /tmp/deployment.yml

bosh deployment /tmp/deployment.yml

yes yes | bosh deploy
