#!/bin/bash

set -e -x

STUBS_DIR=deployments-runtime/${DEPLOYMENT_NAME}/stubs/

chruby 2.1.2

bosh -n target ${BOSH_TARGET}

if ! bosh -n login ${BOSH_USER} ${BOSH_PASSWORD}; then
  echo "Creating director user"
  bosh -n -u admin -p admin create user ${BOSH_USER} ${BOSH_PASSWORD}
fi

case "${INFRASTRUCTURE}" in
  aws)
    bosh upload stemcell "light-bosh-stemcell-latest-aws-xen-ubuntu-trusty-go_agent.tgz" --skip-if-exists
    bosh upload stemcell "light-bosh-stemcell-latest-aws-xen-ubuntu-lucid-go_agent.tgz" --skip-if-exists
    ;;
  warden)
    bosh upload stemcell "bosh-stemcell-60-warden-boshlite-ubuntu-lucid-go_agent.tgz" --skip-if-exists
    bosh upload stemcell "bosh-stemcell-3-warden-boshlite-ubuntu-trusty-go_agent.tgz" --skip-if-exists
    scripts/generate_bosh_lite_stub > ${STUBS_DIR}/bosh_lite_stub.yml
    ;;
  *)
    echo "infrastructure '${INFRASTRUCTURE}' not set up yet"
    exit 1
    ;;
esac

bosh -n upload release "cf-release-created-by-ci.tgz" --rebase --skip-if-exists || true
bosh -n upload release "diego-release-created-by-ci.tgz" --rebase --skip-if-exists || true

pushd cf-release
  ./generate_deployment_manifest ${INFRASTRUCTURE} ${STUBS_DIR}/* > /tmp/cf-deployment.yml

  bosh deployment /tmp/cf-deployment.yml

  yes yes | bosh deploy
popd

pushd diego-release
  ./generate_deployment_manifest ${INFRASTRUCTURE} cf-release ${STUBS_DIR}/* > /tmp/diego-deployment.yml

  bosh deployment /tmp/diego-deployment.yml

  yes yes | bosh deploy
popd
