#!/bin/bash

set -e -x

git submodule update --init --recursive

bosh target ${BOSH_TARGET}

if [ ! -d /tmp/cf-release/.git ]; then
  # clean up after earlier step which will cause an
  # empty /tmp/cf-release to become cached
  rm -rf /tmp/cf-release

  git clone https://github.com/cloudfoundry/cf-release.git /tmp/cf-release
fi

git clone $DEPLOYMENTS_REPO /tmp/deployments

pushd /tmp/cf-release
  ./update

  echo cf | bosh create release
  bosh -n upload release --rebase --skip-if-exists
popd

echo diego | bosh create release
bosh -n upload release --rebase --skip-if-exists

./generate_combo_manifest aws /tmp/cf-release /tmp/deployments/$DEPLOYMENT_NAME/stubs/* > /tmp/deployment.yml

bosh deployment /tmp/deployment.yml

yes yes | bosh deploy
