#!/bin/sh

set -e -x

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path="etcd-certs"
mkdir -p ${depot_path}

# CA to distribute to etcd clients and servers
certstrap --depot-path ${depot_path} init --passphrase '' --common-name diegoCA
mv -f ${depot_path}/diegoCA.crt ${depot_path}/diego-ca.crt
mv -f ${depot_path}/diegoCA.key ${depot_path}/diego-ca.key

# Server certificate to share across the etcd cluster
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name etcd.service.consul --domain '*.etcd.service.consul,etcd.service.consul'
certstrap --depot-path ${depot_path} sign etcd.service.consul --CA diego-ca
mv -f ${depot_path}/etcd.service.consul.key ${depot_path}/server.key
mv -f ${depot_path}/etcd.service.consul.csr ${depot_path}/server.csr
mv -f ${depot_path}/etcd.service.consul.crt ${depot_path}/server.crt

# Client certificate to distribute to jobs that access etcd
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name 'diego etcd client'
certstrap --depot-path ${depot_path} sign diego_etcd_client --CA diego-ca
mv -f ${depot_path}/diego_etcd_client.key ${depot_path}/client.key
mv -f ${depot_path}/diego_etcd_client.csr ${depot_path}/client.csr
mv -f ${depot_path}/diego_etcd_client.crt ${depot_path}/client.crt

# CA to distribute cross etcd peers
certstrap --depot-path ${depot_path} init --passphrase '' --common-name peerCA
mv -f ${depot_path}/peerCA.crt ${depot_path}/peer-ca.crt
mv -f ${depot_path}/peerCA.key ${depot_path}/peer-ca.key

certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name etcd.service.consul --domain '*.etcd.service.consul,etcd.service.consul'
certstrap --depot-path ${depot_path} sign etcd.service.consul --CA peer-ca
mv -f ${depot_path}/etcd.service.consul.key ${depot_path}/peer.key
mv -f ${depot_path}/etcd.service.consul.csr ${depot_path}/peer.csr
mv -f ${depot_path}/etcd.service.consul.crt ${depot_path}/peer.crt
