#!/bin/bash

set -e -x

existing_depot="$1"

if [[ ! -z "$2" ]]; then
  diego_ca_name="$2"
else
  diego_ca_name="cf-diego-ca"
fi

pushd `dirname "$0"`/..
  scripts/generate-bbs-certs         "$diego_ca_name" "$existing_depot"
  scripts/generate-locket-certs      "$diego_ca_name" "$existing_depot"
  scripts/generate-rep-certs         "$diego_ca_name" "$existing_depot"
  scripts/generate-auctioneer-certs  "$diego_ca_name" "$existing_depot"
  scripts/generate-tps-certs         "$diego_ca_name" "$existing_depot"
  scripts/generate-cc-uploader-certs "$diego_ca_name" "$existing_depot"
popd

echo "Outputted certs to diego-certs"
