#!/bin/sh
if [ -z $1 ]; then
  echo "Usage: $0 <path to CF manifest>"
  exit 1
fi

spiff merge manifest-generation/misc-templates/cf-sql-stub.yml \
  manifest-generation/misc-templates/cf-sql-stub-internal.yml \
  manifest-generation/config-from-cf-internal.yml \
  $1
