#!/bin/bash

set -e -x

usage() {
  >&2 echo "    Usage:
    $0 DIEGO_CA_NAME DIEGO_CA_CERT_DIRECTORY

    Ex:
    $0 diegoCA ~/workspace/diego-release/diego-certs/
"
  exit 1
}

ca_name=$1
ca_cert_directory=$2

if [ -z "${ca_name}" ]; then
  >&2 echo "Specify a CA"
  usage
fi

if [ ! -d "${ca_cert_directory}" ]; then
  >&2 echo "Specify location of CA cert and key"
  usage
fi

# Install certstrap
go get -v github.com/square/certstrap

# Place keys and certificates here
output_path="diego-certs/tps-certs"
mkdir -p ${output_path}

client_cn='tps_watcher'
certstrap --depot-path ${ca_cert_directory} request-cert --passphrase '' --common-name $client_cn
certstrap --depot-path ${ca_cert_directory} sign $client_cn --CA $ca_name
mv -f "${ca_cert_directory}/${client_cn}.key" "${output_path}/client.key"
mv -f "${ca_cert_directory}/${client_cn}.csr" "${output_path}/client.csr"
mv -f "${ca_cert_directory}/${client_cn}.crt" "${output_path}/client.crt"
