#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

mkdir -p ${DIEGO_MANIFESTS_DIR}

pushd ${DIEGO_RELEASE_DIR}
$scripts_path/generate-deployment-manifest \
    manifest-generation/bosh-lite-stubs/property-overrides.yml \
    manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
    manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
    manifest-generation/bosh-lite-stubs/iaas-settings.yml \
    manifest-generation/bosh-lite-stubs/additional-jobs.yml \
    ${CF_MANIFESTS_DIR} \
    > ${DIEGO_MANIFESTS_DIR}/diego.yml

    tmpdir=$(mktemp -d /tmp/diego-manifest.XXXXX)

    spiff merge \
      manifest-generation/config-from-cf.yml \
      manifest-generation/config-from-cf-internal.yml \
      ${CF_MANIFESTS_DIR}/cf.yml \
      > ${tmpdir}/config-from-cf.yml

    spiff merge \
      manifest-generation/bosh-lite-stubs/diego-acceptance-tests.yml \
      manifest-generation/bosh-lite-stubs/iaas-settings.yml \
      ${tmpdir}/config-from-cf.yml \
      > ${DIEGO_MANIFESTS_DIR}/diego-acceptance-tests.yml

    spiff merge \
      manifest-generation/bosh-lite-stubs/diego-smoke-tests.yml \
      manifest-generation/bosh-lite-stubs/iaas-settings.yml \
      ${tmpdir}/config-from-cf.yml \
      > ${DIEGO_MANIFESTS_DIR}/diego-smoke-tests.yml

    $scripts_path/generate-benchmarks-manifest \
      ${DIEGO_MANIFESTS_DIR}/diego.yml \
      manifest-generation/benchmark-errand-stubs/default_bosh_lite_benchmark_properties.yml \
      manifest-generation/bosh-lite-stubs/iaas-settings.yml \
      > ${DIEGO_MANIFESTS_DIR}/diego-benchmarks.yml
popd

echo "CF Release Manifest at ${CF_MANIFESTS_DIR}/cf.yml"
echo "Diego Release Manifest at ${DIEGO_MANIFESTS_DIR}/diego.yml"
