#!/bin/bash

set -e

manifest_generation=$(dirname $0)/../manifest-generation

usage() {
  >&2 cat <<EOF
SYNOPSIS:
    Generate a manifest for a Diego deployment to accompany an existing CF deployment.

USAGE:
    $0 <MANDATORY ARGUMENTS> [OPTIONAL ARGUMENTS]

MANDATORY ARGUMENTS:
    -c <cf-path>        Path to CF manifest file.
    -i <iaas-path>      Path to IaaS-settings stub file.
    -p <property-path>  Path to property-overrides stub file.

OPTIONAL ARGUMENTS:
    -n <count-path>     Path to instance-count-overrides stub file.
    -v <versions-path>  Path to release-versions stub file.
    -s <sql-db-path>    Path to SQL stub file.
    -x                  Opt out of deploying etcd with the database vms (requires sql)
    -g                  Opt into using garden-runc-release for cells.
    -b                  Opt into using capi-release for bridge components.
    -d <voldriver-path> Path to voldriver stub file.

EXAMPLE:
    $0 \\
      -c ../cf-release/bosh-lite/deployments/cf.yml \\
      -i manifest-generation/bosh-lite-stubs/iaas-settings.yml \\
      -p manifest-generation/bosh-lite-stubs/property-overrides.yml \\
      -n manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \\
      -v manifest-generation/bosh-lite-stubs/release-versions.yml \\
      -s manifest-generation/bosh-lite-stubs/diego-sql.yml \\
      -x \\
      -d manifest-generation/bosh-lite-stubs/experimental/voldriver/drivers.yml \\
      -g \\
      -b
EOF
  exit 1
}

base_releases="${manifest_generation}/base-releases.yml"
garden_properties=""
bridge_properties=""

while getopts "c:i:p:n:k:v:s:d:krbgx" opt; do
  case $opt in
    c)
      cf_deployment_manifest=$OPTARG
      ;;
    i)
      iaas_settings=$OPTARG
      ;;
    p)
      property_overrides=$OPTARG
      ;;
    n)
      instance_counts=$OPTARG
      ;;
    g)
      garden_properties="${manifest_generation}/garden-runc-properties.yml";
      ;;
    b)
      bridge_properties="${manifest_generation}/capi-bridge-properties.yml";
      ;;
    v)
      release_versions=$OPTARG
      ;;
    s)
      sql_settings=$OPTARG
      ;;
    k)
      >&2 echo "DEPRECATED -k flag: Persistent disk configuration moved to IaaS-settings stub."
      ;;
    r)
      >&2 echo "DEPRECATED -r flag: The cflinuxfs2 rootfs now always comes from its own release."
      ;;
    d)
      voldriver_settings=$OPTARG
      ;;
    x)
      bbs_properties="${manifest_generation}/bbs-overrides-no-etcd.yml"
      ;;
    *)
      echo "Unknown arguments"
      usage
      ;;
  esac
done

if [ -z ${cf_deployment_manifest} ]; then
  >&2 echo "ERROR: CF manifest file is missing"
  argument_error=true
else
  if [ ! -f "${cf_deployment_manifest}" ]; then
    >&2 echo "ERROR: CF manifest '${cf_deployment_manifest}' is not a regular file"
    argument_error=true
  fi
fi

if [ -z ${iaas_settings} ]; then
  >&2 echo "ERROR: IaaS-settings stub file is missing"
  argument_error=true
else
  if [ ! -f "${iaas_settings}" ]; then
    >&2 echo "ERROR: IaaS Setting stub '${iaas_settings}' is not a regular file"
    argument_error=true
  fi
fi

if [ -z ${property_overrides} ]; then
  >&2 echo "ERROR: Property-overrides stub file is missing"
  argument_error=true

else
  if [ ! -f "${property_overrides}" ]; then
    >&2 echo "ERROR: Property-overrides stub '${property_overrides}' is not a regular file"
    argument_error=true
  fi
fi

if [[ ! -z "${sql_settings}" && ! -f "${sql_settings}" ]]; then
  >&2 echo "ERROR: SQL Setting stub '${sql_settings}' is not a regular file"
  argument_error=true
fi

if [[ ! -z "${voldriver_settings}" && ! -f "${voldriver_settings}" ]]; then
  >&2 echo "ERROR: Voldriver Setting stub '${voldriver_settings}' is not a regular file"
  argument_error=true
fi

if [[ ! -z "${instance_counts}" && ! -f "${instance_counts}" ]]; then
  >&2 echo "ERROR: Instance-count-overrides stub '${instance_counts}' is not a regular file"
  argument_error=true
fi

if [[ ! -z "${release_versions}" && ! -f "${release_versions}" ]]; then
  >&2 echo "ERROR: Release-versions stub '${release_versions}' is not a regular file"
  argument_error=true
fi

if [ ! -z $argument_error ]; then
  echo
  usage
fi

tmpdir=$(mktemp -d /tmp/diego-manifest.XXXXX)

spiff merge \
  ${manifest_generation}/config-from-cf.yml \
  ${manifest_generation}/config-from-cf-internal.yml \
  ${cf_deployment_manifest} \
  > ${tmpdir}/config-from-cf.yml

spiff merge \
  ${manifest_generation}/diego.yml \
  ${garden_properties} \
  ${release_versions} \
  ${bbs_properties} \
  ${bridge_properties} \
  ${property_overrides} \
  ${instance_counts} \
  ${sql_settings} \
  ${voldriver_settings} \
  ${iaas_settings} \
  ${tmpdir}/config-from-cf.yml \
  > ${tmpdir}/diego.yml

spiff merge \
  ${manifest_generation}/misc-templates/bosh.yml \
  ${tmpdir}/diego.yml
