#!/bin/bash

set -e -u

TEMPLATE=$(cat <<TEMPLATE

---
director_uuid: %s
properties:
  acceptance_tests:
    api: api.%s.xip.io
    apps_domain: %s.xip.io
TEMPLATE
)

printf "$TEMPLATE" $(bosh status --uuid) $BOSH_TARGET $BOSH_TARGET
