#!/usr/bin/env ruby

raise "Needs one argument of file to mutate" unless ARGV.length == 1

text = File.read(ARGV[0])

text.scan(/{{(.*)}}/).flatten.each do |var|
  if ENV[var]
    text.gsub!("{{#{var}}}", ENV[var].to_s)
  else
    text.gsub!("- #{var}={{#{var}}}", "")
  end
end

File.open(ARGV[0], 'w') { |f| f.write(text) }
