#!/bin/bash

set -x

if [ -z "$1" ]; then
  echo "Needs one argument of file to mutate"
  exit 1
fi

cp $1 "$1.tmp"

cat "$1.tmp" | while read line; do
  [[ "$line" =~ \{\{(.*)\}\} ]]
  if [[ -n "${BASH_REMATCH[1]}" ]]
  then
    VAR_NAME="${BASH_REMATCH[1]}"
    VAR_VALUE=$(eval "echo \${$VAR_NAME}")
    if [ -n "$VAR_VALUE" ]; then
      echo "$line" | sed "s/{{$VAR_NAME}}/$VAR_VALUE/g"
    fi
  else
    echo "$line"
  fi 
done > $1

rm "$1.tmp"

