#!/bin/bash

set -e -x

function run_system_tests() {
  echo RUNNING SYSTEM TESTS
}

case "$DRONE_BRANCH" in
  develop)
    ./scripts/run_integration_tests true
    ;;
  deploy)
    ./scripts/deploy
    ;;
  system-tests)
    run_system_tests
    ;;
esac
