#!/bin/bash

set -e -x

git remote add pipeline git@github.com:cloudfoundry-incubator/diego-release.git

case "$DRONE_BRANCH" in
  HEAD)
    ./scripts/run_integration_tests
    ;;
  develop)
    ./scripts/run_integration_tests
    git push pipeline HEAD:refs/heads/deploy
    ;;
  deploy)
    ./scripts/deploy
    git push pipeline HEAD:refs/heads/system-tests
    ;;
  system-tests)
    ./scripts/run_system_tests
    git push pipeline HEAD:refs/heads/master
    ;;
  *)
    echo "DRONE_BRANCH was not set correctly, was '$DRONE_BRANCH'"
    exit 1
    ;;
esac
