#!/bin/bash

set -e -x -u

case "$GO_STAGE_NAME" in
  integration)
    ./scripts/run_integration_tests
    ;;
  deploy-and-test)
    ./scripts/deploy
    ./scripts/run_system_tests
    ;;
  bless)
    echo "The priest is not in yet"
    exit 1
    ;;
  *)
    echo "GO_STAGE_NAME was not set correctly, was '$GO_STAGE_NAME' -- should have been set by gocd"
    exit 0 # change this to exit 1 once GOCD is real
    ;;
esac
