#!/bin/bash

cd $(dirname $0)/..

set -e -x

./scripts/sync-submodule-config
./scripts/sync-package-specs
./scripts/run_unit_tests
./scripts/run_inigo
./scripts/commit_with_shortlog "$@"

git commit --amend
