#!/bin/bash

cd $(dirname $0)/..

set -e -x

./scripts/sync-submodule-config
./scripts/sync-package-specs
./scripts/run-unit-tests
./scripts/run-inigo
./scripts/commit-with-submodule-log "$@"

git commit --amend
