#!/bin/bash

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

ERROR_CODE=0

SQL_FLAVOR=mysql $scripts_path/run-unit-tests-with-backing-store
ERROR_CODE=$?

SQL_FLAVOR=postgres $scripts_path/run-unit-tests-with-backing-store
let ERROR_CODE+=$?

SQL_FLAVOR=mssql MSSQL_BASE_CONNECTION_STRING=${MSSQL_BASE_CONNECTION_STRING:-"server=localhost;user id=diego;password=Password-123;port=1433"} $scripts_path/run-unit-tests-with-backing-store
let ERROR_CODE+=$?

$scripts_path/run-unit-tests-no-backing-store
let ERROR_CODE+=$?

if [ ${ERROR_CODE} -eq 0 ]; then
  echo "Diego Unit Tests Passed."
else
  echo "Diego Unit Tests Failed!"
fi

exit ${ERROR_CODE}
