#!/bin/bash

set -e

if [ -n "$PACKAGE" ]; then
  ginkgo -r -p "$@" "./src/${PACKAGE}"
else
  pushd ./src/github.com/cloudfoundry/gunk/diegonats/
    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress
  popd

  pushd ./src/github.com/pivotal-golang/cacheddownloader/
    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress
  popd

  pushd src/github.com/cloudfoundry-incubator/
    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress \
      -skipPackage="simulation,inigo,fezzik,garden,garden-linux,dropsonde,candiedyaml,diego-smoke-tests,diego-acceptance-tests,cf-test-helpers,vizzini,veritas" "$@"
  popd
fi
