#!/bin/bash

set -e

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "${SCRIPTS_DIR}/get_paths.sh"

if [ -n "${DIEGO_CI_TARGET}" ]; then
  target="-t ${DIEGO_CI_TARGET}"
else
  target="-t runtime-diego"
fi

build_config=""
if [ "${SQL_FLAVOR}" = "postgres" ]; then
  build_config="${DIEGO_RELEASE_DIR}/scripts/ci/run_unit_postgres.build.yml"
else
  build_config="${DIEGO_RELEASE_DIR}/scripts/ci/run_unit_mysql.build.yml"
fi

fly ${target} execute \
  --privileged \
  --config "${build_config}" \
  --input="diego-release=$DIEGO_RELEASE_DIR" \
  -- "$@"
