#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

pushd ${DIEGO_RELEASE_DIR}/src/code.cloudfoundry.org/vizzini/
ginkgo \
  -nodes=${NODES:-2} \
  -randomizeAllSpecs \
  "$@" \
  -- \
 -bbs-address="https://10.244.16.2:8889" \
 -bbs-client-cert=${DIEGO_RELEASE_DIR}/manifest-generation/bosh-lite-stubs/bbs-certs/client.crt \
 -bbs-client-key=${DIEGO_RELEASE_DIR}/manifest-generation/bosh-lite-stubs/bbs-certs/client.key
popd
