#!/bin/bash

set -e

./scripts/generate-deployment-manifest \
  ~/deployments/bosh-lite/director.yml \
  ~/workspace/docker-registry-release/stubs-for-diego-release/bosh-lite-property-overrides.yml \
  manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
  manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
  manifest-generation/bosh-lite-stubs/iaas-settings.yml \
  manifest-generation/bosh-lite-stubs/additional-jobs.yml \
  ~/deployments/bosh-lite \
  > ~/deployments/bosh-lite/diego.yml

bosh create release --force
bosh -t lite -n upload release
bosh -t lite -d  ~/deployments/bosh-lite/diego.yml -n deploy

pushd ./src/github.com/cloudfoundry-incubator/docker-registry-acceptance-tests/
  export CONFIG=`pwd`/integration_config.json
  ginkgo -r "$@" docker/
  unset CONFIG
popd
