#!/bin/bash

set -e

./scripts/generate-deployment-manifest \
  ~/deployments/bosh-lite/director.yml \
  ~/workspace/docker-registry-release/stubs-for-diego-release/bosh-lite-property-overrides.yml \
  manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
  manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
  manifest-generation/bosh-lite-stubs/iaas-settings.yml \
  ~/deployments/bosh-lite \
  > ~/deployments/bosh-lite/diego.yml

echo "WARNING: targeting BOSH-Lite director"
bosh target lite
bosh create release --force
bosh -n upload release
bosh -n -d  ~/deployments/bosh-lite/diego.yml deploy

pushd ./src/github.com/cloudfoundry-incubator/diego-acceptance-tests/
  export CONFIG=`pwd`/integration_config.json
  ginkgo -r -nodes=3 "$@" docker/
  unset CONFIG
popd
