#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

SKIP_PACKAGES="bbs/measurements,benchmark-bbs,simulation,inigo,fezzik,./garden,garden-linux,dropsonde,candiedyaml,diegocanaryapp,cf-test-helpers,vizzini,veritas,benchmark-bbs,upgrade-stability,volman"

if [ -n "${RUN_VOLMAN}" ]; then
  SKIP_PACKAGES="bbs/measurements,benchmark-bbs,simulation,inigo,fezzik,./garden,garden-linux,dropsonde,candiedyaml,diegocanaryapp,cf-test-helpers,vizzini,veritas,benchmark-bbs,upgrade-stability"
fi

if [ -n "$PACKAGE" ]; then
  ginkgo -r -p "$@" "./src/${PACKAGE}"
else
  pushd $DIEGO_RELEASE_DIR/src/github.com/cloudfoundry/gunk/diegonats/
    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race
  popd

  pushd $DIEGO_RELEASE_DIR/src/github.com/cloudfoundry-incubator/
    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race \
      -skipPackage=${SKIP_PACKAGES} "$@"
  popd
fi
