#!/bin/bash

set -e

cd $(dirname $0)/..

pushd src/github.com/cloudfoundry-incubator/inigo
  for pkg in `find . -type d ! -path . -maxdepth 1`; do
    go test -c ./${pkg} > /dev/null
  done
popd

if [ -n "${DIEGO_CI_TARGET}" ]; then
  target="-t ${DIEGO_CI_TARGET}"
fi

fly -k ${target} execute -p -x -c scripts/ci/run_inigo.build.yml -- "$@"
