#!/bin/bash

set -e

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "${SCRIPTS_DIR}/get_paths.sh"

if [ -n "${DIEGO_CI_TARGET}" ]; then
  target="-t ${DIEGO_CI_TARGET}"
else
  target="-t runtime-diego"
fi

export MYSQL_PASSWORD=password
export MYSQL_USER=root
export SCRIPT=run-unit-tests-with-backing-store
export SQL_FLAVOR=mysql
fly ${target} execute \
  --privileged \
  --config "${DIEGO_RELEASE_DIR}/scripts/ci/run_unit_mysql.build.yml" \
  --input="diego-release=$DIEGO_RELEASE_DIR" \
  -- "$@"
