#!/bin/bash

set -e

./scripts/generate-deployment-manifest \
  ~/deployments/bosh-lite/director.yml \
  manifest-generation/bosh-lite-stubs/property-overrides.yml \
  manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
  manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
  manifest-generation/bosh-lite-stubs/iaas-settings.yml \
  ~/deployments/bosh-lite \
  > ~/deployments/bosh-lite/diego.yml

echo "WARNING: targeting BOSH-Lite director and setting Diego deployment manifest"
bosh target lite
bosh deployment ~/deployments/bosh-lite/diego.yml
bosh create release --force
bosh -n upload release
bosh -n deploy

pushd ./src/github.com/cloudfoundry-incubator/diego-acceptance-tests/

export CONFIG=`pwd`/integration_config.json
ginkgo -r -nodes=3 "$@" diego/
unset CONFIG

popd
