#!/bin/bash

set -e

pushd ./src/github.com/cloudfoundry-incubator/diego-acceptance-tests/
  export CONFIG=`pwd`/integration_config.json
  ginkgo -r -nodes=3 "$@" diego/ security_groups/
  unset CONFIG
popd
