#!/bin/bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. "${SCRIPTS_DIR}/get_paths.sh"

BIN_DIR="${DIEGO_RELEASE_DIR}/bin"
mkdir -p "${BIN_DIR}"
export PATH="${PATH}:${BIN_DIR}"

set -e
pushd "${DIEGO_RELEASE_DIR}/tools/nats-server"
  go mod vendor
  go build -o "$BIN_DIR/nats-server" -mod vendor .
popd
set +e

set -e
pushd "${BIN_DIR}"
  wget https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_linux_amd64.zip
  unzip -oj consul_0.7.0_linux_amd64.zip
  rm consul_0.7.0_linux_amd64.zip
popd
set +e


set -e
${SCRIPTS_DIR}/check-metrics-documentation
set +e

SKIP_PACKAGES="./inigo"
SKIP_PACKAGES="$SKIP_PACKAGES,./auction/simulation"
SKIP_PACKAGES="$SKIP_PACKAGES,./auctioneer/cmd/auctioneer"
SKIP_PACKAGES="$SKIP_PACKAGES,./bbs/cmd/bbs"
SKIP_PACKAGES="$SKIP_PACKAGES,./bbs/db/migrations"
SKIP_PACKAGES="$SKIP_PACKAGES,./bbs/db/sqldb"
SKIP_PACKAGES="$SKIP_PACKAGES,./benchmarkbbs"
SKIP_PACKAGES="$SKIP_PACKAGES,./cf-tcp-router"
SKIP_PACKAGES="$SKIP_PACKAGES,./clock"
SKIP_PACKAGES="$SKIP_PACKAGES,./converger/cmd/converger"
SKIP_PACKAGES="$SKIP_PACKAGES,./diego-upgrade-stability-tests"
SKIP_PACKAGES="$SKIP_PACKAGES,./diegocanaryapp"
SKIP_PACKAGES="$SKIP_PACKAGES,./dropsonde"
SKIP_PACKAGES="$SKIP_PACKAGES,./fezzik"
SKIP_PACKAGES="$SKIP_PACKAGES,./garden"
SKIP_PACKAGES="$SKIP_PACKAGES,./garden-linux"
SKIP_PACKAGES="$SKIP_PACKAGES,./go-loggregator"
SKIP_PACKAGES="$SKIP_PACKAGES,./gorouter"
SKIP_PACKAGES="$SKIP_PACKAGES,./guardian"
SKIP_PACKAGES="$SKIP_PACKAGES,./locket/cmd/locket"
SKIP_PACKAGES="$SKIP_PACKAGES,./locket/db"
SKIP_PACKAGES="$SKIP_PACKAGES,./rep/cmd/rep"
SKIP_PACKAGES="$SKIP_PACKAGES,./rep/generator/internal"
SKIP_PACKAGES="$SKIP_PACKAGES,./route-emitter/cmd/route-emitter"
SKIP_PACKAGES="$SKIP_PACKAGES,./routing-api"
SKIP_PACKAGES="$SKIP_PACKAGES,./trace-logger"
SKIP_PACKAGES="$SKIP_PACKAGES,./uaa-go-client"
SKIP_PACKAGES="$SKIP_PACKAGES,./veritas"
SKIP_PACKAGES="$SKIP_PACKAGES,./vizzini"
SKIP_PACKAGES="$SKIP_PACKAGES,./systemcerts"
SKIP_PACKAGES="$SKIP_PACKAGES,./credhub-cli"
SKIP_PACKAGES="$SKIP_PACKAGES,./cfdot/integration"
SKIP_PACKAGES="$SKIP_PACKAGES,./rfc5424"
SKIP_PACKAGES="$SKIP_PACKAGES,./grootfs"
SKIP_PACKAGES="$SKIP_PACKAGES,./idmapper"
ERROR_CODE=0

if [ -z "${RUN_SQL_TESTS}" ]; then
  SKIP_PACKAGES="$SKIP_PACKAGES,./bbs/db/sqldb"
fi

if [ ! -z "$PACKAGE" ]; then
  ginkgo -r -nodes 8 "$@" "./src/${PACKAGE}"
  exit $?
else
  pushd $DIEGO_RELEASE_DIR/src/code.cloudfoundry.org/ > /dev/null
    go run github.com/onsi/ginkgo/ginkgo -r -keepGoing -nodes 8 -trace -randomizeAllSpecs -progress -race \
      -skipPackage=${SKIP_PACKAGES} "$@"
    let ERROR_CODE+=$?
  popd > /dev/null
  exit $ERROR_CODE
fi
