#!/bin/bash
set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)
workspace=${WORKSPACE:-"${HOME}/workspace"}

echo "checking code for compilation errors..."
pushd "${DIEGO_RELEASE_DIR}/src/code.cloudfoundry.org/inigo" > /dev/null
  for pkg in `find . -maxdepth 1 -type d ! -path . -not -path '*/\.*'`; do
    echo "${pkg}";
    GOOS=linux GOARCH=amd64 go test -c ./${pkg} > /dev/null
  done
popd > /dev/null
echo "compilation check complete"

DIEGO_CI_TARGET="${DIEGO_CI_TARGET:-runtime-diego}"

fly --target "${DIEGO_CI_TARGET}" execute \
    --privileged \
    -c "${DIEGO_RELEASE_DIR}/scripts/ci/run_inigo_grootfs.build.yml" \
    -i diego-release="${DIEGO_RELEASE_DIR}" \
    -i garden-runc-release="${workspace}/garden-runc-release" \
    -i routing-release="${workspace}/routing-release" \
    -- "$@"
