#!/bin/bash

set -e -x

RELEASE_ROOT=$(dirname $(dirname $0))

TMPDIR=${TMPDIR:-/tmp}

rm -rf ${TMPDIR}/diego-release-gopath.*

export GOPATH_ROOT=$(mktemp -d ${TMPDIR}/diego-release-gopath.XXXXX)

export GOPATH=$GOPATH_ROOT
export PATH=$GOPATH_ROOT/bin:$PATH

function copy_to_gopath {
  mkdir -p ${GOPATH_ROOT}/src/$(dirname $1)
  rsync -a src/$(basename $1)/ ${GOPATH_ROOT}/src/$1/
}

# grab and set up our components
for package in \
    github.com/cloudfoundry-incubator/inigo \
    github.com/cloudfoundry-incubator/executor \
    github.com/cloudfoundry-incubator/stager \
    github.com/cloudfoundry-incubator/servistry \
    github.com/cloudfoundry-incubator/linux-smelter \
    github.com/cloudfoundry-incubator/file-server \
    github.com/cloudfoundry-incubator/warden-linux;
    do
  copy_to_gopath $package
done

# install application dependencies
go get github.com/coreos/etcd
go install github.com/coreos/etcd
go get github.com/apcera/gnatsd
go install github.com/apcera/gnatsd

# set up inigo's own dependencies
export GOPATH=${GOPATH}:${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/inigo/Godeps/_workspace
export PATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/inigo/Godeps/_workspace/bin:${PATH}

# set up compile-time $GOPATHs for each component
export LOGGREGATOR_GOPATH=${GOPATH_ROOT}/loggregator
export EXECUTOR_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/executor/Godeps/_workspace:${GOPATH_ROOT}
export STAGER_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/stager/Godeps/_workspace:${GOPATH_ROOT}
export SERVISTRY_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/servistry/Godeps/_workspace:${GOPATH_ROOT}
export FILE_SERVER_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/file-server/Godeps/_workspace:${GOPATH_ROOT}
export LINUX_SMELTER_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/linux-smelter/Godeps/_workspace:${GOPATH_ROOT}
export WARDEN_LINUX_GOPATH=${GOPATH_ROOT}/src/github.com/cloudfoundry-incubator/warden-linux/Godeps/_workspace:${GOPATH_ROOT}

# grab master of loggregator
git clone https://github.com/cloudfoundry/loggregator $LOGGREGATOR_GOPATH --depth 1

pushd $LOGGREGATOR_GOPATH
  git submodule update --init --recursive
popd

cd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/inigo

./scripts/drone-test
