#!/bin/bash

set -e

chruby 2.1.2

set -x -u

# We generate the CF manifest using the stub ${DEPLOYMENT_NAME}/stubs/cf-aws located in the
# ${DEPLOYMENTS_REPO} repository.  That stub is a YAML file with a value at meta.environment
# which happens to equal cf-${DEPLOYMENT_NAME}, and spiff uses the value at that location to
# determine the following BOSH deployment name.
CF_DEPLOYMENT_NAME=cf-${DEPLOYMENT_NAME}

bosh target ${BOSH_TARGET}
bosh login ${BOSH_USER} ${BOSH_PASSWORD}
bosh download manifest ${CF_DEPLOYMENT_NAME} > /tmp/cf-deployment.yml
bosh deployment /tmp/cf-deployment.yml
bosh run errand acceptance_tests
