#!/bin/bash

set -e -x

USE_DRONE=$1

if [ -n "$WORKSPACE" ]; then
  echo "I see you are running on Jenkins"
  echo "Let me gvm that for you."
  . /usr/local/share/gvm/scripts/gvm
  gvm use go1.2
fi

rm -rf diego-release-gopath.*

RELEASE_ROOT=$(dirname $(dirname $0))

export GOPATH_ROOT=$(mktemp -d ${PWD}/diego-release-gopath.XXXXX)

export GOPATH=$GOPATH_ROOT
export PATH=$GOPATH_ROOT/bin:$PATH

function copy_to_gopath {
  mkdir -p ${GOPATH_ROOT}/src/$(dirname $1)
  rsync -a src/$(basename $1)/ ${GOPATH_ROOT}/src/$1/
}

# grab and set up our components
for package in \
    github.com/cloudfoundry-incubator/inigo \
    github.com/cloudfoundry-incubator/executor \
    github.com/cloudfoundry-incubator/stager \
    github.com/pivotal-cf-experimental/garden; do
  copy_to_gopath $package
  export GOPATH=${GOPATH}:${GOPATH_ROOT}/src/$package/Godeps/_workspace
  export PATH=${PATH}:${GOPATH_ROOT}/src/$package/Godeps/_workspace/bin
done

# install application dependencies
for package in github.com/coreos/etcd github.com/apcera/gnatsd; do
  copy_to_gopath $package
  go install $package
done

git clone https://github.com/cloudfoundry/loggregator $GOPATH_ROOT/loggregator
export GOPATH=${GOPATH}:${GOPATH_ROOT}/loggregator

cd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/inigo

if [ "$USE_DRONE" = "true" ]; then
  # for protoc
  apt-get install --yes protobuf-compiler

  ./scripts/drone-test
else
  ./scripts/test
fi
