#!/bin/bash

if [ -n "$PACKAGE" ]; then
  ginkgo -r -p "$@" "./src/${PACKAGE}"
else
  cd src/github.com/cloudfoundry-incubator/

  ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress \
    -skipPackage="simulation,inigo,garden-linux,dropsonde,candiedyaml,diego-smoke-tests,cf-test-helpers"
fi
