#! /bin/bash

go get honnef.co/go/tools/cmd/staticcheck

pids=""
run_staticcheck() {
  staticcheck -checks 'U1000' $1
  pids+=" $!"
}

run_staticcheck "code.cloudfoundry.org/auctioneer/..."
run_staticcheck "code.cloudfoundry.org/bbs/..."
run_staticcheck "code.cloudfoundry.org/benchmarkbbs/..."
run_staticcheck "code.cloudfoundry.org/certsplitter/..."
run_staticcheck "code.cloudfoundry.org/cfdot/..."
run_staticcheck "code.cloudfoundry.org/diego-ssh/..."
run_staticcheck "code.cloudfoundry.org/dockerapplifecycle/..."
run_staticcheck "code.cloudfoundry.org/buildpackapplifecycle/..."
run_staticcheck "code.cloudfoundry.org/fileserver/..."
run_staticcheck "code.cloudfoundry.org/locket/..."
run_staticcheck "code.cloudfoundry.org/rep/..."
run_staticcheck "code.cloudfoundry.org/route-emitter/..."
run_staticcheck "code.cloudfoundry.org/vizzini/..."

exit_code=0
for pid in $pids; do
  wait $pid
  ec=$?
  if [[ $ec -ne 0 ]]; then
    exit_code=1
  fi
done

exit $exit_code

