#!/bin/bash
set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
GO111MODULE=on go get github.com/vito/gosub
FORCE_SUBMODULE_HTTPS="${FORCE_SUBMODULE_HTTPS:-false}"

rm -rf /tmp/packages
cat >> /tmp/packages <<EOF
code.cloudfoundry.org/auction
code.cloudfoundry.org/auctioneer
code.cloudfoundry.org/bbs
code.cloudfoundry.org/benchmarkbbs
code.cloudfoundry.org/buildpackapplifecycle
code.cloudfoundry.org/bytefmt
code.cloudfoundry.org/cacheddownloader
code.cloudfoundry.org/cfdot
code.cloudfoundry.org/credhub-cli
code.cloudfoundry.org/diego-ssh
code.cloudfoundry.org/diego-upgrade-stability-tests
code.cloudfoundry.org/dockerapplifecycle
code.cloudfoundry.org/dockerdriver
code.cloudfoundry.org/durationjson
code.cloudfoundry.org/ecrhelper
code.cloudfoundry.org/eventhub
code.cloudfoundry.org/executor
code.cloudfoundry.org/fileserver
garden
code.cloudfoundry.org/goshims
grootfs
guardian
code.cloudfoundry.org/healthcheck
idmapper
code.cloudfoundry.org/inigo
code.cloudfoundry.org/localdriver
code.cloudfoundry.org/locket
code.cloudfoundry.org/operationq
code.cloudfoundry.org/rep
code.cloudfoundry.org/route-emitter
code.cloudfoundry.org/routing-api
code.cloudfoundry.org/routing-info
code.cloudfoundry.org/systemcerts
code.cloudfoundry.org/trace-logger
code.cloudfoundry.org/uaa-go-client
code.cloudfoundry.org/vendor
code.cloudfoundry.org/vizzini
code.cloudfoundry.org/volman
code.cloudfoundry.org/workpool
EOF

cat /tmp/packages | xargs -s 1048576 gosub sync --force-https=$FORCE_SUBMODULE_HTTPS
