#!/bin/bash

set -e

while read bosh_pkg type go_pkg; do
  pushd packages/$bosh_pkg >/dev/null
    {
      cat spec | grep -v '# gosub'
      gosub list -${type} $go_pkg | \
        sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
    } > spec.new

    mv spec.new spec

    if [ "$(git status --porcelain spec | cut -c2)" = "M" ]; then
      echo packages/$bosh_pkg/spec
    fi
  popd >/dev/null
done < <(
  echo auctioneer app github.com/cloudfoundry-incubator/auctioneer
  echo converger app github.com/cloudfoundry-incubator/converger
  echo docker-circus app github.com/cloudfoundry-incubator/docker-circus/...
  echo etcd app github.com/coreos/etcd
  echo etcd_metrics_server app github.com/cloudfoundry-incubator/etcd-metrics-server
  echo executor app github.com/cloudfoundry-incubator/executor
  echo file_server app github.com/cloudfoundry-incubator/file-server
  echo linux-circus app github.com/cloudfoundry-incubator/linux-circus/...
  echo nsync app github.com/cloudfoundry-incubator/nsync/...
  echo rep app github.com/cloudfoundry-incubator/rep
  echo route_emitter app github.com/cloudfoundry-incubator/route-emitter
  echo runtime_metrics_server app github.com/cloudfoundry-incubator/runtime-metrics-server
  echo stager app github.com/cloudfoundry-incubator/stager
  echo tps app github.com/cloudfoundry-incubator/tps
  echo smoke-tests test github.com/cloudfoundry-incubator/diego-smoke-tests
)
