#!/bin/sh

if [ "$1" == "--help" ]; then
  echo "Usage: $0 REPO_NAME"
  echo ""
  echo "This script updates the requested submodule to the latest commit on origin."
  echo "It will then prepare a commit message for you containing all of the commit messages between the previous submodule sha and the new submodule sha."
  exit 0
fi

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 REPO_NAME"
  exit 1
fi

echo "Skipping cf-acceptance-tests"
echo "See: https://www.pivotaltracker.com/story/show/70793548"
echo ""

repo=$1
release=`pwd`

set -e

# buckle up
git submodule foreach \
  "if (pwd | grep  src/$repo | grep -q -v cf-acceptance-tests); then" \
  '  sub=`pwd`;' \
  '  git checkout master;' \
  '  git pull;' \
  '  git submodule update --init --recursive;' \
  "  cd $release;" \
  '  git add $sub;' \
  'fi'

$(dirname $0)/staged_shortlog -c
